<a href="https://colab.research.google.com/github/Tom-Jung/IO_with_python/blob/main/Ch6_1.%20%EB%AC%BC%EA%B0%80%ED%8C%8C%EA%B8%89%ED%9A%A8%EA%B3%BC%20%EB%93%B1%20%EB%B6%84%EC%84%9D_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

3부문 총, 국산, 수입거래표 불러오기

In [3]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs.csv"  # 3부문의 총거래표 불러오기
Tt_3 = pd.read_csv(url_Tt_3)

url_Dt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_3_secs.csv"  # 3부문의 국산거래표 불러오기
Dt_3 = pd.read_csv(url_Dt_3)

url_It_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_3_secs.csv"  # 3부문의 수입거래표 불러오기
It_3 = pd.read_csv(url_It_3)


In [4]:
Tt = Tt_3.to_numpy()
Dt = Dt_3.to_numpy()
It = It_3.to_numpy()

In [5]:
Tt_1 = Tt[0:10,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[4.000e+00 3.800e+01 1.100e+01 5.300e+01 1.800e+01 0.000e+00 1.000e+00
  1.900e+01 7.200e+01]
 [1.600e+01 9.440e+02 4.010e+02 1.361e+03 2.130e+02 1.670e+02 6.280e+02
  1.008e+03 2.369e+03]
 [7.000e+00 2.570e+02 6.930e+02 9.570e+02 1.032e+03 4.320e+02 1.310e+02
  1.595e+03 2.552e+03]
 [2.700e+01 1.239e+03 1.105e+03 2.371e+03 1.263e+03 5.990e+02 7.600e+02
  2.622e+03 4.993e+03]
 [7.000e+00 1.970e+02 7.140e+02 9.180e+02 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]
 [2.000e+01 1.520e+02 2.980e+02 4.700e+02 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]
 [5.000e+00 1.440e+02 2.300e+02 3.790e+02 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]
 [1.000e+00 6.000e+01 1.000e+02 1.610e+02 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]
 [3.300e+01 5.530e+02 1.342e+03 1.928e+03 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]
 [6.000e+01 1.792e+03 2.447e+03 4.299e+03 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]]
국산거래표 : 
 [[ 4.000e+00  3.100e+01  1.000

In [7]:
Ct = Tt_1[-1,0:3]  # 산출액
Ct

array([  60., 1792., 2447.])

In [8]:
Ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
Ct_m

array([[  60., 1792., 2447.],
       [  60., 1792., 2447.],
       [  60., 1792., 2447.]])

In [10]:
At = Tt_1[0:3,0:3]/Ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/Ct_m  # 국산 투입계수
Ai = Im_1[0:3,0:3]/Ct_m  # 수입 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)
print('수입투입계수표 : \n', Ai)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ai = pd.DataFrame(Ai.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.06666667 0.02120536 0.0044953 ]
 [0.26666667 0.52678571 0.16387413]
 [0.11666667 0.14341518 0.28320392]]
국산투입계수표 : 
 [[0.06666667 0.01729911 0.00408664]
 [0.25       0.328125   0.1315897 ]
 [0.11666667 0.13560268 0.2631794 ]]
수입투입계수표 : 
 [[0.         0.00390625 0.00040866]
 [0.01666667 0.19866071 0.03228443]
 [0.         0.0078125  0.02002452]]


### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [11]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans, '\n')
print('국산투입계수의 전치행렬: \n', Ad_trans, '\n')
print('수입투입계수의 전치행렬: \n', Ai_trans, '\n')

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬

print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

총투입계수의 전치행렬 : 
 [[0.06666667 0.26666667 0.11666667]
 [0.02120536 0.52678571 0.14341518]
 [0.0044953  0.16387413 0.28320392]] 

국산투입계수의 전치행렬: 
 [[0.06666667 0.25       0.11666667]
 [0.01729911 0.328125   0.13560268]
 [0.00408664 0.1315897  0.2631794 ]] 

수입투입계수의 전치행렬: 
 [[0.         0.01666667 0.        ]
 [0.00390625 0.19866071 0.0078125 ]
 [0.00040866 0.03228443 0.02002452]] 

국산투입계수 전치행렬의 역행렬: 
 [[1.08092021 0.45201623 0.25433867]
 [0.03012689 1.55662423 0.29124759]
 [0.01137552 0.28050647 1.41060738]]


In [12]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.08092021, 0.03012689, 0.01137552],
       [0.45201623, 1.55662423, 0.28050647],
       [0.25433867, 0.29124759, 1.41060738]])

In [18]:
Va_r = Tt_1[-2,0:3]/Ct  # 부가가치율
Va_m = np.diag(Va_r)    # 부가가치율 대각행렬

Lv = Va_m@Lf   #부가가치유발계수
Li = Ai@Lf  #수입유발계수

Aw_r = Tt_1[-6,0:3]/Ct #  피용자보수율
Aw_m = np.diag(Aw_r)
print('피용자보수율: \n', Aw_m,'\n')

피용자보수율: 
 [[0.11666667 0.         0.        ]
 [0.         0.10993304 0.        ]
 [0.         0.         0.29178586]] 



#### 임금인상의 물가파급효과

In [24]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = ((Lf_trans@Aw_m)@delta_all_w).round(3)

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = ((Lf_trans@Aw_m)@delta_par_w).round(3)

print('모든 상품의 임금이 10% 상승시: \n', delta_all_Pw, '\n')
print('공산품의 임금이 10% 상승시: \n', delta_par_Pw, '\n')


모든 상품의 임금이 10% 상승시: 
 [[2.5  ]
 [2.596]
 [4.438]] 

공산품의 임금이 10% 상승시: 
 [[0.497]
 [1.711]
 [0.308]] 



#### 내생부분(중간투입품) 가격변동의 물가파급효과

In [27]:
#### 중간투입되는 서비스의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,2,0).reshape([2,3])  # 서비스(sectors3) 행 삭제
Ad_exd_serv = np.delete(Ad_exd_row,2,1).reshape([2,2])  # 서비스(sectors3) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제거한 국산투입계수 : \n', Ad_exd_serv.round(3))

Lf_Ad = np.linalg.inv(np.identity(2)-Ad_exd_serv)
print('물가변동이 발생한 부문을 제거한 유발계수 : \n', Lf_Ad.round(3))

A_Pr_sec2 = np.concatenate((Ad_trans[0,2].reshape([1,1]),Ad_trans[1,2].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a31, a32)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2.round(3))

#서비스 물가 10% 상승시 파급효과

delta_serv_Pw = Lf_Ad@A_Pr_sec2*10
print('서비스 10% 상승시 다른 부문의 물가변동 : \n', delta_serv_Pw.round(3))

물가변동이 발생한 부문을 제거한 국산투입계수 : 
 [[0.067 0.25 ]
 [0.017 0.328]]
물가변동이 발생한 부문을 제거한 유발계수 : 
 [[1.079 0.401]
 [0.028 1.499]]
물가변동이 발생한 부문의 국산투입계수 : 
 [[0.117]
 [0.136]]
서비스 10% 상승시 다른 부문의 물가변동 : 
 [[1.803]
 [2.065]]


#### 수입농산품 가격변동의 물가파급효과


In [ ]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입농산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

수입농산품 가격 10% 상승시 다른 부문의 물가변동 : 
 [[0.019]
 [0.062]
 [0.017]]


### 환율변동 효과

In [ ]:
Ex_rate = np.array([10,10,10]).reshape([3,1]) # 환율 10% 상승
delta_Ex_rate =  ((Lf_trans @Ai_trans)@Ex_rate).reshape([3,1])

print('환율 10% 상승시 물가변동 : \n', delta_Ex_rate)

환율 10% 상승시 물가변동 : 
 [[1.265]
 [3.433]
 [1.336]]


### 환율변동과 수입농산품 효과

In [28]:
Ex_arg = np.array([21,10,10]).reshape([3,1]) # 환율 10% 및 수입농산품 10% 상승
delta_Ex_arg =  ((Lf_trans @Ai_trans)@Ex_arg).reshape([3,1])

print('환율 및 수입농 10% 상승시 물가변동 : \n', delta_Ex_arg )

환율 및 수입농 10% 상승시 물가변동 : 
 [[1.28574987]
 [3.50157309]
 [1.35405659]]


In [ ]:
#pandas로 내보내기

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_serv_Pw = pd.DataFrame(delta_serv_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 서비스 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승
df_delta_Ex_rate = pd.DataFrame(delta_Ex_rate.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 환율 10% 상승
df_delta_Ex_arg = pd.DataFrame(delta_Ex_arg.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 환율 및 수입농산품 10% 상승

In [ ]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_serv_Pw.to_csv('서비스 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')
df_delta_Ex_rate.to_csv('환율 10% 상승.csv')
df_delta_Ex_arg.to_csv('환율 및 수입농산품 10% 상승.csv')