<a href="https://colab.research.google.com/github/Tom-Jung/IO_with_python/blob/main/Ch6_2.%20%EC%82%B0%EC%B6%9C%20%EB%B3%80%EB%8F%99%EC%9A%94%EC%9D%B8%20%EB%B6%84%ED%95%B4_3%EB%B6%80%EB%AC%B8_%EC%B1%85%EC%9E%90%EC%9A%A9(%EC%A1%B0%EC%9B%90).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 책자 예제용(조단위) 거래표 이용

In [75]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

### 산출 변동요인분해

In [76]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/Total_Matrix_2015_cst_3sectors.csv"  # 불변 2015년 총거래표(3부문)
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/Imported_Matrix_2015_cst_3sectors.csv"  # 불변 2015년 수입거래표(3부문)
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/Imported_Matrix_2015_cst_3sectors.csv"  # 불변 2015년 국산거래표(3부문)
Dom_cst_15 = pd.read_csv(url_dom)

In [77]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/Total_Matrix_2010_cst_3sectors.csv"  # 불변 2010년 총거래표(3부문)
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/Imported_Matrix_2010_cst_3sectors.csv"  # 불변 2010년 수입거래표(3부문)
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/Domestic_Matrix_2010_cst_3sectors.csv"  # 불변 2010년 국산거래표(3부문)
Dom_cst_10 = pd.read_csv(url_dom)

In [78]:
S1= Tot_cst_15.iloc[:,1:].to_numpy().astype(float)
I1 = Imp_cst_15.iloc[:,1:].to_numpy().astype(float)
S0 = Tot_cst_10.iloc[:,1:].to_numpy().astype(float)
I0 = Imp_cst_10.iloc[:,1:].to_numpy().astype(float)

In [79]:
SS1 = np.concatenate((S1[:8,],np.zeros((1,9)), S1[8:10,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지

In [80]:
SS0 = S0[0:3,0:3].astype(float)  # 내생항목 3x3
SS1 = S1[0:3,0:3].astype(float)
SS1.shape

(3, 3)

In [81]:
II0 = I0[0:3,0:3]  # 수입 내생항목 3x3
II1 = I1[0:3,0:3]

In [82]:
DD0 =SS0 - II0  # 국산 내생항목 3x3
DD1 =SS1 - II1
DD0

array([[  4.129,  28.996,   8.603],
       [ 16.765, 510.283, 235.219],
       [  5.354, 209.094, 427.31 ]])

In [83]:
TM0 = I0[0:3,8]  # 총수입벡터
TM1 = I1[0:3,8]
TM0

array([  9.798, 416.95 ,  72.427])

In [84]:
IM0 = I0[0:3,3]  # 중간재수입벡터
IM1 = I1[0:3,3]
IM0

array([  7.69 , 325.084,  48.331])

In [85]:
IF0 = I0[0:3,7]  # 최종재수입벡터
IF1 = I1[0:3,7]
IF0

array([ 2.108, 91.866, 24.096])

In [86]:
SFC0 = S0[0:3,4]  # 최종수요-소비
SFC1 = S1[0:3,4]
SFC0

array([ 16.01 , 166.514, 740.29 ])

In [87]:
SFI0 = S0[0:3,5] # 최종수요-투자
SFI1 = S1[0:3,5]
SFI0

array([  2.646, 137.44 , 310.398])

In [88]:
SF0 = S0[0:3,7] # 최종수요합계
SF1 = S1[0:3,7]
SF0

array([  19.485,  760.437, 1129.235])

In [89]:
EX0 = S0[0:3,6] # 수출
EX1 = S1[0:3,6]
EX0

array([  0.83 , 456.483,  78.546])

In [90]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1
DF0

array([  18.655,  303.954, 1050.689])

In [91]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


2010년 소비합계 :  922.814
2015년 소비합계 :  1054.8999999999999
2010년 투자합계 :  450.48400000000004
2015년 투자합계 :  489.601
2010년 수출합계 :  535.859
2015년 수출합계 :  716.951


In [92]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [93]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [94]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [95]:
C0 = S0[-1,0:3].T.reshape([3,1])  # 총산출액
C1 = S1[-1,0:3].T.reshape([3,1])
C0

array([[  59.105],
       [1430.838],
       [1746.898]])

In [96]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)
TC0

array([3236.841])

In [97]:
V0 = S0[-1,0:3].T - S0[3,0:3].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:3].T - S1[3,0:3].T
V1

array([  33.259,  485.04 , 1119.153])

In [98]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1
AV1

array([[5.41924656e-01, 7.90327837e+00, 1.82355634e+01],
       [1.94365907e-02, 2.83457830e-01, 6.54034061e-01],
       [1.61670182e-02, 2.35775294e-01, 5.44014159e-01]])

In [99]:
C0

array([[  59.105],
       [1430.838],
       [1746.898]])

In [100]:
CT0 = np.tile(C0, reps=[1,3])   # Ct벡터를 반복해여 행렬(3x3)로 만듬
CT1 = np.tile(C1, reps=[1,3])
CT1

array([[  61.372,   61.372,   61.372],
       [1711.154, 1711.154, 1711.154],
       [2057.213, 2057.213, 2057.213]])

In [101]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [102]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [103]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [104]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [105]:
RD0 = np.linalg.inv(np.eye(3) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(3) - AD1)

In [106]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

# np.nan_to_num(AM0, copy=False)
# np.nan_to_num(AM1, copy=False)

In [107]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐 및 라스파이레스 방식으로 산출액 변동을 분해하여 평균으로 성장요인을 분해
- 파쉐 방식

In [108]:
# TC1 = ((RD1@(np.eye(3)-M1))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD1@(np.eye(3)-M1))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [109]:
# TI1 = ((RD1@(np.eye(3)-M1))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD1@(np.eye(3)-M1))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [110]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape
# TQS/1000000

In [111]:
TQS=(RD1@(np.eye(3)-M1))@(DF1-DF0).reshape([3,1]) # 국내최종수요증감효과

In [112]:
TTE= RD1@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000

In [113]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
T4

array([[ -1.44586732],
       [-24.6666165 ],
       [ -8.59386349]])

In [114]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

array([[-2.65600823],
       [ 6.68283903],
       [30.74901506]])

In [133]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TQS + TTE + T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1
DCT

array([[0.00215215],
       [0.00259916],
       [0.00082169]])

In [149]:
np.set_printoptions(precision=3)

In [156]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
PGD1015 = (np.concatenate((SUM, SUM1), axis=0))
PGD1015_f = PGD1015.round(3)
print(np.round(PGD1015_f,3))

[[ 2.267e+00  2.265e+00  2.000e-03  2.393e+00  5.202e+00 -1.229e+00
  -1.446e+00 -2.656e+00]
 [ 2.803e+02  2.803e+02  3.000e-03  6.172e+01  2.570e+02 -2.040e+01
  -2.467e+01  6.683e+00]
 [ 3.103e+02  3.103e+02  1.000e-03  2.144e+02  8.677e+01 -1.305e+01
  -8.594e+00  3.075e+01]
 [ 5.929e+02  5.929e+02  6.000e-03  2.786e+02  3.489e+02 -3.468e+01
  -3.471e+01  3.478e+01]]


In [152]:
import numpy as np

a = np.array([1.0, 2.5, 3.46567, 4.0, 5.2])
np.set_printoptions(precision=3)
print(a)

[1.    2.5   3.466 4.    5.2  ]


In [153]:
PGD1015_ff = pd.DataFrame(PGD1015_f,columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [154]:
PGD1015_ff

15-10산출액(A)  요인별합계(B)    B-A  국내최종수요증감액       수출   최종재수입   중간재수입    기술변화
농산품        2.267     2.265  0.002      2.393    5.202  -1.229  -1.446  -2.656
공산품      280.316   280.313  0.003     61.724  256.973 -20.400 -24.667   6.683
서비스      310.315   310.314  0.001    214.444   86.770 -13.055  -8.594  30.749
계        592.898   592.892  0.006    278.561  348.946 -34.684 -34.706  34.776

- 라스파이레스식

In [119]:
# TC1 = ((RD0@(np.eye(3)-M0))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD0@(np.eye(3)-M0))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [ ]:
# TI1 = ((RD0@(np.eye(3)-M0))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD0@(np.eye(3)-M0))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [ ]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape

In [ ]:
TQS=(RD0@(np.eye(3)-M0))@(DF1-DF0).reshape([3,1])
# TQS/1000000

In [ ]:
T2 = (RD0@ED2).reshape([3,1]) # 수출규모증가효과
T22 = (RD0@ED3) .reshape([3,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [ ]:
TTE= RD0@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000

In [ ]:
T3 = ((RD0@(M1 - M0))@DF1).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD0@(II1 - AM0)))@C1[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI

array([[ -2.51646901,  -1.61889291,  -0.89757609],
       [-49.48964707, -21.28180553, -28.20784154],
       [-25.04596103, -15.45777561,  -9.58818542]])

In [ ]:
T5 = (RD0@(AA-(AM0-II0)))@C1 # 기술변화효과
T5.shape
T5

array([[-4.16754891],
       [ 8.10677449],
       [36.04485881]])

In [ ]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
LGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
# LGD1015_f = (LGD1015/1000).round(1)
LGD1015_f

array([[ 2.00000000e+00,  2.00000000e+00, -1.77635684e-15,
         2.55747030e+00,  6.12654761e+00, -1.61889291e+00,
        -8.97576092e-01, -4.16754891e+00],
       [ 2.82000000e+02,  2.82000000e+02, -1.70530257e-13,
         6.32771344e+01,  2.60105738e+02, -2.12818055e+01,
        -2.82078415e+01,  8.10677449e+00],
       [ 3.12000000e+02,  3.12000000e+02, -5.68434189e-14,
         2.14297530e+02,  8.67035723e+01, -1.54577756e+01,
        -9.58818542e+00,  3.60448588e+01],
       [ 5.96000000e+02,  5.96000000e+02, -2.29150032e-13,
         2.80132135e+02,  3.52935858e+02, -3.83584741e+01,
        -3.86936030e+01,  3.99840844e+01]])

In [ ]:
LGD1015_ff = pd.DataFrame((LGD1015_f).round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [ ]:
LGD1015_ff

15-10산출액(A)  요인별합계(B)  B-A  국내최종수요증감액       수출   최종재수입   중간재수입    기술변화
농산품          2.0       2.0 -0.0      2.557    6.127  -1.619  -0.898  -4.168
공산품        282.0     282.0 -0.0     63.277  260.106 -21.282 -28.208   8.107
서비스        312.0     312.0 -0.0    214.298   86.704 -15.458  -9.588  36.045
계          596.0     596.0 -0.0    280.132  352.936 -38.358 -38.694  39.984

In [ ]:
PGD1015_ff.to_csv('산출액변동요인_파쉐.csv', encoding="utf-8-sig")
LGD1015_ff.to_csv('산출액변동요인_라스파이레스.csv', encoding="utf-8-sig")

In [ ]:
Ctbr_Pa =  PGD1015_f[:,3:]
Ctbr_La =  LGD1015_f[:,3:]
Ctbr_La

array([[  2.5574703 ,   6.12654761,  -1.61889291,  -0.89757609,
         -4.16754891],
       [ 63.27713436, 260.10573822, -21.28180553, -28.20784154,
          8.10677449],
       [214.29752996,  86.70357226, -15.45777561,  -9.58818542,
         36.04485881],
       [280.13213463, 352.93585808, -38.35847405, -38.69360305,
         39.98408439]])

In [ ]:
sm_gap_Pa = PGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La = LGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La

array([[  2.],
       [282.],
       [312.],
       [596.]])

In [ ]:
sm_gap1_Pa = np.tile(sm_gap_Pa, reps=[1,5]) # 요인별 합계를 33x16으로 반복
sm_gap1_La = np.tile(sm_gap_La, reps=[1,5]) # 요인별 합계를 33x16으로 반복
sm_gap1_La

array([[  2.,   2.,   2.,   2.,   2.],
       [282., 282., 282., 282., 282.],
       [312., 312., 312., 312., 312.],
       [596., 596., 596., 596., 596.]])

In [ ]:
Ctrb_f_Pa = (Ctbr_Pa/sm_gap1_Pa)*100  # 각 항목별 기여율
Ctrb_f_La = (Ctbr_La/sm_gap1_La)*100  # 각 항목별 기여율
Ctrb_f_Pa

array([[ 119.25501099,  268.4222033 ,  -75.26408976,  -35.87312514,
        -176.53999938],
       [  21.85403435,   91.01706858,   -7.01420374,   -8.26431501,
           2.40741582],
       [  69.22418809,   27.81067729,   -4.46666302,   -2.58106284,
          10.01286048],
       [  46.97868187,   58.52447829,   -5.90961828,   -5.38183673,
           5.78829485]])

In [ ]:
Ctrb_ff_Pa = pd.DataFrame(Ctrb_f_Pa,columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [ ]:
Ctrb_ff_La = pd.DataFrame(Ctrb_f_La,columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [ ]:
Ctrb_ff_Pa.to_csv('항목별 기여율_파쉐.csv', encoding="utf-8-sig")
Ctrb_ff_La.to_csv('항목별 기여율_라스파이레스.csv', encoding="utf-8-sig")