<a href="https://colab.research.google.com/github/Tom-Jung/IO_with_python/blob/main/Ch8.%20%EA%B5%AD%EA%B0%80%20%EA%B0%84%20%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%ED%9A%A8%EA%B3%BC%20%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [255]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [256]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [257]:
# from google.colab import drive
# drive.mount('/content/drive')

In [258]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [259]:
url_icio = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/ICIO_4cons_3secs_1Fd_2020.csv"  # 4국 3부문 2020년 ICIO 불러오기
Icio = pd.read_csv(url_icio)
Icio.head()

단위  억달러   한국  한국.1  한국.2    중국   중국.1  중국.2   미국 미국.1 미국.2  ROW ROW.1  \
0  국가   산업  농산품   공산품   서비스   농산품    공산품   서비스  농산품  공산품  서비스  농산품   공산품   
1  한국  농산품   25   247    91     0      0     0    0    3    1    1     3   
2  한국  공산품  111  5200  2638    59   1097   340   10  194  177   67  1120   
3  한국  서비스   62  2314  5377    19    198   147    2   29   82   14   203   
4  중국  농산품    1     6     2  4912  10317  1336    6   19    4   33   106   

  ROW.2   한국.3  중국.3  미국.3 ROW.3     총계  
0   서비스   최종수요  최종수요  최종수요  최종수요    총수요  
1     1    143     0     1     2    518  
2   536   1623   278   349   891  14690  
3   345  11605   105    81   263  20846  
4    21      2  5712     6    76  22559

In [260]:
Icio_1 = Icio.to_numpy()
Icio_2=Icio_1[1:,2:].astype(float)
Icio_2

array([[     25.,     247.,      91.,       0.,       0.,       0.,
              0.,       3.,       1.,       1.,       3.,       1.,
            143.,       0.,       1.,       2.,     518.],
       [    111.,    5200.,    2638.,      59.,    1097.,     340.,
             10.,     194.,     177.,      67.,    1120.,     536.,
           1623.,     278.,     349.,     891.,   14690.],
       [     62.,    2314.,    5377.,      19.,     198.,     147.,
              2.,      29.,      82.,      14.,     203.,     345.,
          11605.,     105.,      81.,     263.,   20846.],
       [      1.,       6.,       2.,    4912.,   10317.,    1336.,
              6.,      19.,       4.,      33.,     106.,      21.,
              2.,    5712.,       6.,      76.,   22559.],
       [     10.,     585.,     235.,    4625.,   84294.,   37897.,
             42.,     882.,    1179.,     270.,    5551.,    3633.,
            253.,   28453.,    1978.,    6876.,  176763.],
       [      2.,      79

### 한국 1, 중국2, 미국3, ROW4

#### 산업구조
##### 국가별 산업 비중

###### 가. 산업구조

In [261]:
Mt = Icio_2
Va = Mt[-2,:12].reshape([1,12]) # 산업별 부가가치
Ct = Mt[-1,:12].reshape([1,12])  # 산업별 산출액
Va

array([[   256.,   3975.,  10762.,   9980.,  41148.,  84394.,   1998.,
         24291., 177144.,  23285.,  88535., 330938.]])

In [262]:
# 산출액기준

KOR_ct = (Ct[:,:3]/(Ct[-1,:3].sum())*100)  # 한국 산업별 비중
CHN_ct = (Ct[:,3:6]/(Ct[-1,3:6].sum())*100) # 중국 산업별 비중
USA_ct = (Ct[:,6:9]/(Ct[-1,6:9].sum())*100)  # 미국 산업별 비중
ROW_ct = (Ct[:,9:12]/(Ct[-1,9:12].sum())*100) # ROW 산업별 비중

WORLD_ct_sm = Ct[:,:12].sum()
WORLD_agr_ct = Ct[:,0]+Ct[:,3]+Ct[:,6]+Ct[:,9]
WORLD_manu_ct = Ct[:,1]+Ct[:,4]+Ct[:,7]+Ct[:,10]
WORLD_ser_ct = Ct[:,2]+Ct[:,5]+Ct[:,8]+Ct[:,11]

WORLD_ct = np.hstack((WORLD_agr_ct,WORLD_manu_ct,WORLD_ser_ct))/WORLD_ct_sm*100
IND_CT_CONS = np.vstack((KOR_ct,CHN_ct,USA_ct,ROW_ct,WORLD_ct))
print('산출액 기준 국가별 산업 비중 ', '\n', IND_CT_CONS.round(1))


산출액 기준 국가별 산업 비중  
 [[ 1.4 40.7 57.8]
 [ 6.2 48.2 45.6]
 [ 1.3 16.6 82. ]
 [ 4.6 29.4 66. ]
 [ 4.2 31.  64.8]]


In [263]:
# 부가가치기준

KOR_va = (Va[:,:3]/(Va[-1,:3].sum())*100)  # 한국 산업별 비중
CHN_va = (Va[:,3:6]/(Va[-1,3:6].sum())*100) # 중국 산업별 비중
USA_va = (Va[:,6:9]/(Va[-1,6:9].sum())*100)  # 미국 산업별 비중
ROW_va = (Va[:,9:12]/(Va[-1,9:12].sum())*100) # ROW 산업별 비중

WORLD_va_sm = Va[:,:12].sum()
WORLD_agr_va = Va[:,0]+Va[:,3]+Va[:,6]+Va[:,9]
WORLD_manu_va = Va[:,1]+Va[:,4]+Va[:,7]+Va[:,10]
WORLD_ser_va = Va[:,2]+Va[:,5]+Va[:,8]+Va[:,11]

WORLD_va = np.hstack((WORLD_agr_va,WORLD_manu_va,WORLD_ser_va))/WORLD_va_sm*100

IND_VA_CONS = np.vstack((KOR_va,CHN_va,USA_va,ROW_va,WORLD_va))
print('부가가치 기준 국가별 산업 비중 ', '\n', IND_VA_CONS.round(1))

부가가치 기준 국가별 산업 비중  
 [[ 1.7 26.5 71.8]
 [ 7.4 30.4 62.3]
 [ 1.  11.9 87.1]
 [ 5.3 20.  74.7]
 [ 4.5 19.8 75.7]]


In [264]:
WGT_by_CONS = np.hstack((IND_CT_CONS,IND_VA_CONS))
print('국가별 산업 비중', '\n', WGT_by_CONS.round(1))

국가별 산업 비중 
 [[ 1.4 40.7 57.8  1.7 26.5 71.8]
 [ 6.2 48.2 45.6  7.4 30.4 62.3]
 [ 1.3 16.6 82.   1.  11.9 87.1]
 [ 4.6 29.4 66.   5.3 20.  74.7]
 [ 4.2 31.  64.8  4.5 19.8 75.7]]


In [265]:
CONS_wgt_df = pd.DataFrame(WGT_by_CONS.round(1), columns = [['산출액기준','산출액기준','산출액기준','부가가치기준','부가가치기준','부가가치기준'],
                                                         ['농업', '제조업', '서비스업','농업', '제조업', '서비스업']],
                     index=['한국', '중국', '미국', 'ROW', '전세계']) # 변수명 붙여서 pandas로 내보내기
CONS_wgt_df

산출액기준             부가가치기준            
       농업   제조업  서비스업     농업   제조업  서비스업
한국    1.4  40.7  57.8    1.7  26.5  71.8
중국    6.2  48.2  45.6    7.4  30.4  62.3
미국    1.3  16.6  82.0    1.0  11.9  87.1
ROW   4.6  29.4  66.0    5.3  20.0  74.7
전세계   4.2  31.0  64.8    4.5  19.8  75.7

In [266]:
CONS_wgt_df.to_csv('국가별 산업 비중.csv', encoding='utf_8-sig')

#### 산업별국가비중
###### 산출액기준

In [267]:
# 산출액기준

Agr_ct_cons = np.hstack((Ct[:,0],Ct[:,3],Ct[:,6],Ct[:,9]))
Manu_ct_cons = np.hstack((Ct[:,1],Ct[:,4],Ct[:,7],Ct[:,10]))
Ser_ct_cons = np.hstack((Ct[:,2],Ct[:,5],Ct[:,8],Ct[:,11]))

All_ct_cons = np.hstack((Ct[-1,:3].sum(),Ct[-1,3:6].sum(),Ct[-1,6:9].sum(),Ct[-1,9:12].sum()))
All_ct_cons

array([ 36054., 366725., 358448., 904421.])

In [268]:
Agr_ct_cons_wgt = (Agr_ct_cons/Agr_ct_cons.sum())*100
Manu_ct_cons_wgt = (Manu_ct_cons/Manu_ct_cons.sum())*100
Ser_ct_cons_wgt = (Ser_ct_cons/Ser_ct_cons.sum())*100
All_ct_cons_wgt = (All_ct_cons/All_ct_cons.sum())*100

Cons_ct_ind = np.vstack((Agr_ct_cons_wgt,Manu_ct_cons_wgt,Ser_ct_cons_wgt,All_ct_cons_wgt,))
print('산출액 기준 산업별 국가 비중', '\n', Cons_ct_ind.round(1))

산출액 기준 산업별 국가 비중 
 [[ 0.7 32.5  7.  59.8]
 [ 2.8 34.2 11.5 51.4]
 [ 1.9 15.5 27.2 55.3]
 [ 2.2 22.  21.5 54.3]]


###### 부가가치기준

In [269]:
# 부가가치기준

Agr_va_cons = np.hstack((Va[:,0],Va[:,3],Va[:,6],Va[:,9]))
Manu_va_cons = np.hstack((Va[:,1],Va[:,4],Va[:,7],Va[:,10]))
Ser_va_cons = np.hstack((Va[:,2],Va[:,5],Va[:,8],Va[:,11]))

All_va_cons = np.hstack((Va[-1,:3].sum(),Va[-1,3:6].sum(),Va[-1,6:9].sum(),Va[-1,9:12].sum()))
All_va_cons

array([ 14993., 135522., 203433., 442758.])

In [270]:
Agr_va_cons_wgt = (Agr_va_cons/Agr_va_cons.sum())*100
Manu_va_cons_wgt = (Manu_va_cons/Manu_va_cons.sum())*100
Ser_va_cons_wgt = (Ser_va_cons/Ser_va_cons.sum())*100
All_va_cons_wgt = (All_va_cons/All_va_cons.sum())*100

Cons_va_ind = np.vstack((Agr_va_cons_wgt,Manu_va_cons_wgt,Ser_va_cons_wgt,All_va_cons_wgt,))
print('부가가치 기준 산업별 국가 비중', '\n', Cons_va_ind.round(1))

부가가치 기준 산업별 국가 비중 
 [[ 0.7 28.1  5.6 65.6]
 [ 2.5 26.1 15.4 56.1]
 [ 1.8 14.  29.4 54.9]
 [ 1.9 17.  25.5 55.6]]


In [271]:
WGT_by_INDS = np.hstack((Cons_ct_ind,Cons_va_ind))
WGT_by_INDS

array([[ 0.747, 32.514,  6.97 , 59.77 ,  0.721, 28.098,  5.625, 65.556],
       [ 2.843, 34.205, 11.532, 51.421,  2.517, 26.051, 15.379, 56.053],
       [ 1.931, 15.508, 27.237, 55.324,  1.784, 13.99 , 29.366, 54.86 ],
       [ 2.165, 22.017, 21.52 , 54.298,  1.882, 17.01 , 25.534, 55.574]])

In [272]:
INDS_wgt_df = pd.DataFrame(WGT_by_INDS.round(1), columns = [['산출액기준','산출액기준','산출액기준','산출액기준','부가가치기준','부가가치기준','부가가치기준','부가가치기준'],
                                                         ['한국', '중국', '미국','ROW', '한국', '중국', '미국','ROW']],
                     index=['농업', '제조업', '서비스업', '전부문']) # 변수명 붙여서 pandas로 내보내기
INDS_wgt_df

산출액기준                   부가가치기준                  
        한국    중국    미국   ROW     한국    중국    미국   ROW
농업     0.7  32.5   7.0  59.8    0.7  28.1   5.6  65.6
제조업    2.8  34.2  11.5  51.4    2.5  26.1  15.4  56.1
서비스업   1.9  15.5  27.2  55.3    1.8  14.0  29.4  54.9
전부문    2.2  22.0  21.5  54.3    1.9  17.0  25.5  55.6

In [273]:
INDS_wgt_df.to_csv('산업별 국가 비중.csv', encoding='utf_8-sig')

## 국가별 투입배분구조 및 수출입은 각 산업별로 구할 필요가 없으므로 각 국의 3개 산업을 통합하여 표를 재구성

In [274]:
Cd_for_nae = np.array([[1,1,1,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합
       [0,0,0,1,1,1,0,0,0,0,0,0],
       [0,0,0,0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,0,0,0,1,1,1]])

In [275]:
A_nae = (Cd_for_nae@Mt[:12,:12])@Cd_for_nae.T
A_nae

array([[ 16065.,   1860.,    498.,   2290.],
       [  1036., 204892.,   2532.,  11935.],
       [   546.,   1584., 135890.,  11479.],
       [  2830.,  17395.,  13911., 422941.]])

In [276]:
Va_rw = Mt[-3:,:12]@Cd_for_nae.T # 순생산물세와 부가가치 통합
Va_rw

array([[   584.,   5472.,   2184.,  13018.],
       [ 14993., 135522., 203433., 442758.],
       [ 36054., 366725., 358448., 904421.]])

In [277]:
Fd_rw = Cd_for_nae@Mt[:12,12:16]  # 최종수요
Fd_rw

array([[ 13371.,    383.,    431.,   1156.],
       [   338., 135197.,   2335.,   8460.],
       [   176.,    638., 201657.,   6478.],
       [   702.,   3838.,   9858., 432946.]])

In [278]:
Fd_txva=Mt[12:,12:16]   # 최종수요 세금
Fd_txva

array([[  737.,  4879.,  5227., 24770.],
       [    0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.]])

In [279]:
Nae_vact = np.vstack((A_nae,Va_rw))
Fd_all = np.vstack((Fd_rw,Fd_txva))

In [280]:
Mt_1sec = np.hstack((Nae_vact,Fd_all)) # 1산업 ICIO
print('1산업_4개국 ICIO', '\n', Mt_1sec)

1산업_4개국 ICIO 
 [[ 16065.   1860.    498.   2290.  13371.    383.    431.   1156.]
 [  1036. 204892.   2532.  11935.    338. 135197.   2335.   8460.]
 [   546.   1584. 135890.  11479.    176.    638. 201657.   6478.]
 [  2830.  17395.  13911. 422941.    702.   3838.   9858. 432946.]
 [   584.   5472.   2184.  13018.    737.   4879.   5227.  24770.]
 [ 14993. 135522. 203433. 442758.      0.      0.      0.      0.]
 [ 36054. 366725. 358448. 904421.      0.      0.      0.      0.]]


In [281]:
Nae_vact.shape

(7, 4)

In [282]:
Fd_all.shape

(7, 4)

In [283]:
Icio_1sec_df = pd.DataFrame(Mt_1sec, columns = ['한국', '중국', '미국','ROW', '한국_fd', '중국_fd', '미국_fd','ROW_fd'],
                     index=['한국', '중국', '미국','ROW','세금','부가가치','총투입액']) # 변수명 붙여서 pandas로 내보내기

Icio_1sec_df

한국        중국        미국       ROW    한국_fd     중국_fd     미국_fd  \
한국    16065.0    1860.0     498.0    2290.0  13371.0     383.0     431.0   
중국     1036.0  204892.0    2532.0   11935.0    338.0  135197.0    2335.0   
미국      546.0    1584.0  135890.0   11479.0    176.0     638.0  201657.0   
ROW    2830.0   17395.0   13911.0  422941.0    702.0    3838.0    9858.0   
세금      584.0    5472.0    2184.0   13018.0    737.0    4879.0    5227.0   
부가가치  14993.0  135522.0  203433.0  442758.0      0.0       0.0       0.0   
총투입액  36054.0  366725.0  358448.0  904421.0      0.0       0.0       0.0   

        ROW_fd  
한국      1156.0  
중국      8460.0  
미국      6478.0  
ROW   432946.0  
세금     24770.0  
부가가치       0.0  
총투입액       0.0

In [284]:
Icio_1sec_df.to_csv('1국가_1산업.csv', encoding='utf_8-sig')

#### 국가별 투입구조

In [285]:
One_diag = np.identity(n=4)
Zero_diag = np.where(One_diag == 1, 0, 1)
Zero_diag

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [286]:
Dom=Mt_1sec[:4,:4]*One_diag
Dom_sm=Dom.sum(axis=1).reshape([4,1])
Dom_sm

array([[ 16065.],
       [204892.],
       [135890.],
       [422941.]])

In [287]:
Imp=Mt_1sec[:4,:4]*Zero_diag

Imp_kor = np.delete(Imp[:,0], np.where(Imp[:,0] == 0))
Imp_chn = np.delete(Imp[:,1], np.where(Imp[:,1] == 0))
Imp_usa = np.delete(Imp[:,2], np.where(Imp[:,2] == 0))
Imp_row = np.delete(Imp[:,3], np.where(Imp[:,3] == 0))

Imp_4cons = np.vstack((Imp_kor,Imp_chn,Imp_usa,Imp_row))
Imp_4cons

array([[ 1036.,   546.,  2830.],
       [ 1860.,  1584., 17395.],
       [  498.,  2532., 13911.],
       [ 2290., 11935., 11479.]])

In [288]:
Imp

array([[    0.,  1860.,   498.,  2290.],
       [ 1036.,     0.,  2532., 11935.],
       [  546.,  1584.,     0., 11479.],
       [ 2830., 17395., 13911.,     0.]])

In [289]:
Imp_kor_sm = Imp_kor.sum() # 수입중간투입합
Imp_chn_sm = Imp_chn.sum()
Imp_usa_sm = Imp_usa.sum()
Imp_row_sm = Imp_row.sum()
Imp_tot = np.vstack((Imp_kor_sm,Imp_chn_sm,Imp_usa_sm,Imp_row_sm))
Imp_tot

array([[ 4412.],
       [20839.],
       [16941.],
       [25704.]])

In [290]:
Tip_kor = Dom_sm[0]+Imp_kor_sm #총중간투입액
Tip_chn = Dom_sm[1]+Imp_chn_sm
Tip_usa = Dom_sm[2]+Imp_usa_sm
Tip_row = Dom_sm[3]+Imp_row_sm
Tip_tot = np.vstack((Tip_kor,Tip_chn,Tip_usa,Tip_row))
Tip_tot.shape

(4, 1)

In [291]:
Mt_1sec

array([[ 16065.,   1860.,    498.,   2290.,  13371.,    383.,    431.,
          1156.],
       [  1036., 204892.,   2532.,  11935.,    338., 135197.,   2335.,
          8460.],
       [   546.,   1584., 135890.,  11479.,    176.,    638., 201657.,
          6478.],
       [  2830.,  17395.,  13911., 422941.,    702.,   3838.,   9858.,
        432946.],
       [   584.,   5472.,   2184.,  13018.,    737.,   4879.,   5227.,
         24770.],
       [ 14993., 135522., 203433., 442758.,      0.,      0.,      0.,
             0.],
       [ 36054., 366725., 358448., 904421.,      0.,      0.,      0.,
             0.]])

In [292]:
Tx = Mt_1sec[-3,0:4].reshape([4,1])
Tx_sm = Tx.sum(axis=1)
Tx

array([[  584.],
       [ 5472.],
       [ 2184.],
       [13018.]])

In [293]:
Va_1sec = Mt_1sec[-2,0:4].reshape([4,1])
Va_1sec

array([[ 14993.],
       [135522.],
       [203433.],
       [442758.]])

In [294]:
Tot_input = Tip_tot+Tx.reshape([4,1])+Va_1sec.reshape([4,1])
Tot_input

array([[ 36054.],
       [366725.],
       [358448.],
       [904421.]])

In [295]:
Input_mat = np.hstack((Dom_sm,Imp_4cons,Imp_tot,Tip_tot, Tx, Va_1sec.reshape([4,1]), Tot_input))
Input_sm = Input_mat.sum(axis=0)

In [296]:
Input_strc = np.vstack((Input_mat,Input_sm))
Input_strc

array([[  16065.,    1036.,     546.,    2830.,    4412.,   20477.,
            584.,   14993.,   36054.],
       [ 204892.,    1860.,    1584.,   17395.,   20839.,  225731.,
           5472.,  135522.,  366725.],
       [ 135890.,     498.,    2532.,   13911.,   16941.,  152831.,
           2184.,  203433.,  358448.],
       [ 422941.,    2290.,   11935.,   11479.,   25704.,  448645.,
          13018.,  442758.,  904421.],
       [ 779788.,    5684.,   16597.,   45615.,   67896.,  847684.,
          21258.,  796706., 1665648.]])

In [297]:
Input_strc_ratio = Input_strc/np.tile(Input_strc[:,-1].reshape([5,1]),reps=[1,9])*100
print('국가별 투입구조', '\n', Input_strc_ratio.round(1))

국가별 투입구조 
 [[ 44.6   2.9   1.5   7.8  12.2  56.8   1.6  41.6 100. ]
 [ 55.9   0.5   0.4   4.7   5.7  61.6   1.5  37.  100. ]
 [ 37.9   0.1   0.7   3.9   4.7  42.6   0.6  56.8 100. ]
 [ 46.8   0.3   1.3   1.3   2.8  49.6   1.4  49.  100. ]
 [ 46.8   0.3   1.    2.7   4.1  50.9   1.3  47.8 100. ]]


In [298]:
Input_strc_df = pd.DataFrame(Input_strc, columns = ['국산품', '중국', '미국','ROW', '수입품', '중간투입액', '순생산물세','부가가치','총투입액'],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Input_strc_df

국산품      중국       미국      ROW      수입품     중간투입액    순생산물세      부가가치  \
한국    16065.0  1036.0    546.0   2830.0   4412.0   20477.0    584.0   14993.0   
중국   204892.0  1860.0   1584.0  17395.0  20839.0  225731.0   5472.0  135522.0   
미국   135890.0   498.0   2532.0  13911.0  16941.0  152831.0   2184.0  203433.0   
ROW  422941.0  2290.0  11935.0  11479.0  25704.0  448645.0  13018.0  442758.0   
전세계  779788.0  5684.0  16597.0  45615.0  67896.0  847684.0  21258.0  796706.0   

          총투입액  
한국     36054.0  
중국    366725.0  
미국    358448.0  
ROW   904421.0  
전세계  1665648.0

In [299]:
Input_strc_ratio_df = pd.DataFrame(Input_strc_ratio.round(1), columns = ['국산품', '중국', '미국','ROW', '수입품', '중간투입액', '순생산물세','부가가치','총투입액'],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Input_strc_ratio_df

국산품   중국   미국  ROW   수입품  중간투입액  순생산물세  부가가치   총투입액
한국   44.6  2.9  1.5  7.8  12.2   56.8    1.6  41.6  100.0
중국   55.9  0.5  0.4  4.7   5.7   61.6    1.5  37.0  100.0
미국   37.9  0.1  0.7  3.9   4.7   42.6    0.6  56.8  100.0
ROW  46.8  0.3  1.3  1.3   2.8   49.6    1.4  49.0  100.0
전세계  46.8  0.3  1.0  2.7   4.1   50.9    1.3  47.8  100.0

In [300]:
Input_strc_df.to_csv('국가별 투입구조.csv', encoding='utf_8-sig')
Input_strc_ratio_df.to_csv('국가별 투입구조 비중.csv', encoding='utf_8-sig')

#### 국가별 배분구조

In [301]:
Imp_dstr = Imp.sum(axis=1).reshape([4,1])
Imp_dstr

array([[ 4648.],
       [15503.],
       [13609.],
       [34136.]])

In [302]:
Id_tot = Dom_sm + Imp_dstr
Id_tot

array([[ 20713.],
       [220395.],
       [149499.],
       [457077.]])

In [303]:
Fd_dom = (Mt_1sec[0:4,4:8]*One_diag).sum(axis=1).reshape([4,1])
Fd_imp = (Mt_1sec[0:4,4:8]*Zero_diag).sum(axis=1).reshape([4,1])
Fd_tot = Fd_dom + Fd_imp
Fd_dom

array([[ 13371.],
       [135197.],
       [201657.],
       [432946.]])

In [304]:
Tot_dmd = Id_tot + Fd_tot
Tot_dmd

array([[ 36054.],
       [366725.],
       [358448.],
       [904421.]])

In [305]:
Dstr_mat = np.hstack((Dom_sm,Imp_dstr, Id_tot, Fd_dom, Fd_imp, Fd_tot,Tot_dmd))
Dstr_sm = Dstr_mat.sum(axis=0)

In [306]:
Dstr_strc = np.vstack((Dstr_mat,Dstr_sm))
Dstr_strc

array([[  16065.,    4648.,   20713.,   13371.,    1970.,   15341.,
          36054.],
       [ 204892.,   15503.,  220395.,  135197.,   11133.,  146330.,
         366725.],
       [ 135890.,   13609.,  149499.,  201657.,    7292.,  208949.,
         358448.],
       [ 422941.,   34136.,  457077.,  432946.,   14398.,  447344.,
         904421.],
       [ 779788.,   67896.,  847684.,  783171.,   34793.,  817964.,
        1665648.]])

In [307]:
Dstr_strc_ratio = Dstr_strc/np.tile(Dstr_strc[:,-1].reshape([5,1]),reps=[1,7])*100
print('국가별 배분구조', '\n', Dstr_strc_ratio.round(1))

국가별 배분구조 
 [[ 44.6  12.9  57.4  37.1   5.5  42.6 100. ]
 [ 55.9   4.2  60.1  36.9   3.   39.9 100. ]
 [ 37.9   3.8  41.7  56.3   2.   58.3 100. ]
 [ 46.8   3.8  50.5  47.9   1.6  49.5 100. ]
 [ 46.8   4.1  50.9  47.    2.1  49.1 100. ]]


In [308]:
Dstr_strc_df = pd.DataFrame(Dstr_strc, columns = [['중간수요', '중간수요', '중간수요','최종수요', '최종수요', '최종수요', '총수요'],
                                                  ['자국', '타국', '중간수요계','자국', '타국', '최종수요계', '총수요계']],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Dstr_strc_df

중간수요                         최종수요                           총수요
           자국       타국     중간수요계        자국       타국     최종수요계       총수요계
한국    16065.0   4648.0   20713.0   13371.0   1970.0   15341.0    36054.0
중국   204892.0  15503.0  220395.0  135197.0  11133.0  146330.0   366725.0
미국   135890.0  13609.0  149499.0  201657.0   7292.0  208949.0   358448.0
ROW  422941.0  34136.0  457077.0  432946.0  14398.0  447344.0   904421.0
전세계  779788.0  67896.0  847684.0  783171.0  34793.0  817964.0  1665648.0

In [309]:
Dstr_strc_ratio_df = pd.DataFrame(Dstr_strc_ratio.round(1), columns = [['중간수요', '중간수요', '중간수요','최종수요', '최종수요', '최종수요', '총수요'],
                                                  ['자국', '타국', '중간수요계','자국', '타국', '최종수요계', '총수요계']],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Dstr_strc_ratio_df

중간수요              최종수요               총수요
       자국    타국 중간수요계    자국   타국 최종수요계   총수요계
한국   44.6  12.9  57.4  37.1  5.5  42.6  100.0
중국   55.9   4.2  60.1  36.9  3.0  39.9  100.0
미국   37.9   3.8  41.7  56.3  2.0  58.3  100.0
ROW  46.8   3.8  50.5  47.9  1.6  49.5  100.0
전세계  46.8   4.1  50.9  47.0  2.1  49.1  100.0

In [310]:
Dstr_strc_df.to_csv('국가별 배분구조.csv', encoding='utf_8-sig')
Dstr_strc_ratio_df.to_csv('국가별 배분구조 비중.csv', encoding='utf_8-sig')

#### 국가간 수출구조

In [311]:
Id = Mt_1sec[:4,:4].astype(float)  # 중간수요
Fd = Mt_1sec[:4:,4:].astype(float) # 최종수요

In [312]:
np.fill_diagonal(Id,0) # 자국 0으로 만들기
np.fill_diagonal(Fd,0) # 자국 0으로 만들기

In [313]:
Trade = Id + Fd
Trade_sm_rw = Trade.sum(axis=1).reshape([4,1])
Trade_sm_rw

array([[ 6618.],
       [26636.],
       [20901.],
       [48534.]])

In [314]:
Trade_rw = np.hstack((Trade,Trade_sm_rw))
Exp_ratio = (Trade_rw/Trade_sm_rw)*100
print('국가 간 수출구조', '\n', Exp_ratio.round(1))

국가 간 수출구조 
 [[  0.   33.9  14.   52.1 100. ]
 [  5.2   0.   18.3  76.6 100. ]
 [  3.5  10.6   0.   85.9 100. ]
 [  7.3  43.7  49.    0.  100. ]]


In [315]:
Exp_mat_df = pd.DataFrame(Exp_ratio.round(1), columns = ['한국', '중국', '미국','ROW', '전세계'],
                                       index=['한국', '중국', '미국','ROW']) # 변수명 붙여서 pandas로 내보내기

Exp_mat_df

한국    중국    미국   ROW    전세계
한국   0.0  33.9  14.0  52.1  100.0
중국   5.2   0.0  18.3  76.6  100.0
미국   3.5  10.6   0.0  85.9  100.0
ROW  7.3  43.7  49.0   0.0  100.0

In [316]:
Exp_mat_df.to_csv('국가 간 수출 구조.csv', encoding='utf_8-sig')

국가간 수입구조

In [317]:
Trade_sm_col = Trade.sum(axis=0).reshape([1,4])
Trade_sm_col

array([[ 5628., 25698., 29565., 41798.]])

In [318]:
Trade_col = np.vstack((Trade,Trade_sm_col))
Imp_ratio = (Trade_col/Trade_sm_col)*100
print('국가 간 수입 구조', '\n', Imp_ratio.round(1))

국가 간 수입 구조 
 [[  0.    8.7   3.1   8.2]
 [ 24.4   0.   16.5  48.8]
 [ 12.8   8.6   0.   43. ]
 [ 62.8  82.6  80.4   0. ]
 [100.  100.  100.  100. ]]


In [319]:
Imp_mat_df = pd.DataFrame(Imp_ratio.round(1), columns = ['한국', '중국', '미국','ROW'],
                                       index=['한국', '중국', '미국','ROW', '전세계']) # 변수명 붙여서 pandas로 내보내기

Imp_mat_df

한국     중국     미국    ROW
한국     0.0    8.7    3.1    8.2
중국    24.4    0.0   16.5   48.8
미국    12.8    8.6    0.0   43.0
ROW   62.8   82.6   80.4    0.0
전세계  100.0  100.0  100.0  100.0

In [320]:
Imp_mat_df.to_csv('국가 간 수입 구조.csv', encoding='utf_8-sig')

### 국가 간 산업연관효과분석

[TiVA2022_Indicators_Guide](TiVA2022_Indicators_Guide.pdf)

In [321]:
PROD = Icio_2[-1,:12].astype(float) # 산출액
VALU = Icio_2[-2, 0:12].astype(float) # 부가가치
TAX = Icio_2[-3, 0:12].astype(float) # 순생산물세
PROD_VASH = VALU/PROD
Fd = Icio_2[:12, 12:16]
TAX

array([   6.,  227.,  351.,  120., 2861., 2491.,   26.,  679., 1479.,
        436., 4177., 8405.])

In [322]:
Ct_m = np.tile(PROD, reps=[15,1]) # 산출액을 12번 행반복
Nae = Icio_2[:15,0:12]   # 거래표

Ad =(Nae/Ct_m)  # 투입계수
print('투입계수', '\n', Ad.round(3))

투입계수 
 [[0.048 0.017 0.004 0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.214 0.354 0.127 0.003 0.006 0.002 0.002 0.003 0.001 0.002 0.004 0.001]
 [0.12  0.158 0.258 0.001 0.001 0.001 0.    0.    0.    0.    0.001 0.001]
 [0.002 0.    0.    0.218 0.058 0.008 0.001 0.    0.    0.001 0.    0.   ]
 [0.019 0.04  0.011 0.205 0.477 0.226 0.009 0.015 0.004 0.007 0.021 0.006]
 [0.004 0.005 0.006 0.084 0.133 0.216 0.001 0.002 0.001 0.001 0.003 0.003]
 [0.004 0.001 0.    0.003 0.001 0.    0.161 0.033 0.001 0.002 0.001 0.   ]
 [0.01  0.011 0.004 0.002 0.003 0.001 0.151 0.223 0.043 0.004 0.01  0.002]
 [0.008 0.008 0.007 0.002 0.002 0.002 0.159 0.2   0.318 0.004 0.008 0.007]
 [0.006 0.002 0.001 0.009 0.003 0.    0.029 0.008 0.    0.166 0.053 0.006]
 [0.041 0.094 0.028 0.017 0.054 0.015 0.044 0.074 0.011 0.131 0.354 0.095]
 [0.019 0.024 0.021 0.01  0.013 0.01  0.023 0.023 0.013 0.109 0.196 0.311]
 [0.012 0.015 0.017 0.005 0.016 0.015 0.005 0.011 0.005 0.011 0.016 0.014]
 [0.494 0.271 0.51

In [323]:
Ad_df = pd.DataFrame(Ad.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW', '순생산물세','부가가치', '산출액'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스','순생산물세','부가가치', '산출액']])

Ad_df.index.names=['국가', '상품']
Ad_df

한국                   중국                   미국                \
               농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스   
국가    상품                                                                     
한국    농산품    0.048  0.017  0.004  0.000  0.000  0.000  0.000  0.000  0.000   
      공산품    0.214  0.354  0.127  0.003  0.006  0.002  0.002  0.003  0.001   
      서비스    0.120  0.158  0.258  0.001  0.001  0.001  0.000  0.000  0.000   
중국    농산품    0.002  0.000  0.000  0.218  0.058  0.008  0.001  0.000  0.000   
      공산품    0.019  0.040  0.011  0.205  0.477  0.226  0.009  0.015  0.004   
      서비스    0.004  0.005  0.006  0.084  0.133  0.216  0.001  0.002  0.001   
미국    농산품    0.004  0.001  0.000  0.003  0.001  0.000  0.161  0.033  0.001   
      공산품    0.010  0.011  0.004  0.002  0.003  0.001  0.151  0.223  0.043   
      서비스    0.008  0.008  0.007  0.002  0.002  0.002  0.159  0.200  0.318   
ROW   농산품    0.006  0.002  0.001  0.009  0.003  0.000  0.029  0.008  0.000   
      공산품    0.041  0.094  0.028  0.017  0.054  0.015  0.044  0.074  0.011   
      서비스    0.019  0.024  0.021  0.010  0.013  0.010  0.023  0.023  0.013   
순생산물세 순생산물세  0.012  0.015  0.017  0.005  0.016  0.015  0.005  0.011  0.005   
부가가치  부가가치   0.494  0.271  0.516  0.442  0.233  0.504  0.413  0.408  0.602   
산출액   산출액    1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000   

               ROW                
               농산품    공산품    서비스  
국가    상품                          
한국    농산품    0.000  0.000  0.000  
      공산품    0.002  0.004  0.001  
      서비스    0.000  0.001  0.001  
중국    농산품    0.001  0.000  0.000  
      공산품    0.007  0.021  0.006  
      서비스    0.001  0.003  0.003  
미국    농산품    0.002  0.001  0.000  
      공산품    0.004  0.010  0.002  
      서비스    0.004  0.008  0.007  
ROW   농산품    0.166  0.053  0.006  
      공산품    0.131  0.354  0.095  
      서비스    0.109  0.196  0.311  
순생산물세 순생산물세  0.011  0.016  0.014  
부가가치  부가가치   0.561  0.333  0.554  
산출액   산출액    1.000  1.000  1.000

## 생산유발계수(Lf)

In [324]:
# 생산유발계수

Lf = np.linalg.inv(np.identity(12)-Ad[:12,])    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([12,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합
print('생산유발계수', '\n', Lf)

생산유발계수 
 [[1.059 0.03  0.011 0.    0.001 0.    0.    0.    0.    0.    0.    0.   ]
 [0.404 1.631 0.282 0.015 0.026 0.013 0.008 0.01  0.003 0.006 0.014 0.005]
 [0.257 0.352 1.41  0.006 0.01  0.006 0.003 0.004 0.001 0.003 0.005 0.003]
 [0.011 0.015 0.006 1.328 0.165 0.061 0.006 0.005 0.002 0.004 0.008 0.003]
 [0.102 0.175 0.073 0.636 2.156 0.632 0.046 0.061 0.02  0.038 0.089 0.035]
 [0.029 0.047 0.026 0.25  0.385 1.389 0.012 0.016 0.006 0.011 0.024 0.012]
 [0.007 0.004 0.002 0.005 0.004 0.001 1.203 0.053 0.004 0.005 0.004 0.001]
 [0.027 0.034 0.016 0.009 0.014 0.007 0.256 1.323 0.085 0.014 0.027 0.01 ]
 [0.032 0.04  0.026 0.013 0.017 0.01  0.36  0.404 1.494 0.02  0.035 0.023]
 [0.021 0.026 0.011 0.024 0.025 0.011 0.056 0.028 0.005 1.221 0.109 0.027]
 [0.17  0.306 0.128 0.115 0.223 0.102 0.151 0.191 0.046 0.295 1.657 0.235]
 [0.107 0.165 0.094 0.072 0.117 0.064 0.109 0.114 0.046 0.279 0.493 1.523]]


부가가치유발계수(Lv)

In [325]:
Va_r = (Icio_2[-2,:12]+Icio_2[-3,:12])/PROD # 부가가치율(순생산물세포함)
Va_r

array([0.506, 0.286, 0.533, 0.448, 0.249, 0.519, 0.419, 0.419, 0.608,
       0.572, 0.349, 0.568])

In [326]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬

In [327]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([12,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합
print('부가가치유발계수', '\n', Lv_sm_rw)

부가가치유발계수 
 [[ 0.536  0.015  0.006  0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.558]
 [ 0.116  0.467  0.081  0.004  0.008  0.004  0.002  0.003  0.001  0.002
   0.004  0.001  0.691]
 [ 0.137  0.188  0.751  0.003  0.005  0.003  0.002  0.002  0.001  0.001
   0.003  0.001  1.098]
 [ 0.005  0.007  0.003  0.595  0.074  0.027  0.003  0.002  0.001  0.002
   0.004  0.001  0.723]
 [ 0.025  0.044  0.018  0.158  0.537  0.157  0.011  0.015  0.005  0.009
   0.022  0.009  1.011]
 [ 0.015  0.024  0.013  0.13   0.2    0.721  0.006  0.008  0.003  0.006
   0.013  0.006  1.146]
 [ 0.003  0.002  0.001  0.002  0.002  0.001  0.504  0.022  0.002  0.002
   0.002  0.     0.541]
 [ 0.011  0.014  0.007  0.004  0.006  0.003  0.107  0.554  0.036  0.006
   0.011  0.004  0.763]
 [ 0.02   0.024  0.016  0.008  0.011  0.006  0.218  0.245  0.908  0.012
   0.021  0.014  1.503]
 [ 0.012  0.015  0.006  0.014  0.014  0.006  0.032  0.016  0.003  0.698
   0.062  0.015  0.895]
 [ 0.059  0.107  0.045  0.04   0

In [328]:
Lf_df = pd.DataFrame(Lf.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['국가', '상품']
Lf_df

한국                   중국                   미국                  ROW  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
국가  상품                                                                          
한국  농산품  1.059  0.030  0.011  0.000  0.001  0.000  0.000  0.000  0.000  0.000   
    공산품  0.404  1.631  0.282  0.015  0.026  0.013  0.008  0.010  0.003  0.006   
    서비스  0.257  0.352  1.410  0.006  0.010  0.006  0.003  0.004  0.001  0.003   
중국  농산품  0.011  0.015  0.006  1.328  0.165  0.061  0.006  0.005  0.002  0.004   
    공산품  0.102  0.175  0.073  0.636  2.156  0.632  0.046  0.061  0.020  0.038   
    서비스  0.029  0.047  0.026  0.250  0.385  1.389  0.012  0.016  0.006  0.011   
미국  농산품  0.007  0.004  0.002  0.005  0.004  0.001  1.203  0.053  0.004  0.005   
    공산품  0.027  0.034  0.016  0.009  0.014  0.007  0.256  1.323  0.085  0.014   
    서비스  0.032  0.040  0.026  0.013  0.017  0.010  0.360  0.404  1.494  0.020   
ROW 농산품  0.021  0.026  0.011  0.024  0.025  0.011  0.056  0.028  0.005  1.221   
    공산품  0.170  0.306  0.128  0.115  0.223  0.102  0.151  0.191  0.046  0.295   
    서비스  0.107  0.165  0.094  0.072  0.117  0.064  0.109  0.114  0.046  0.279   

                       
           공산품    서비스  
국가  상품                 
한국  농산품  0.000  0.000  
    공산품  0.014  0.005  
    서비스  0.005  0.003  
중국  농산품  0.008  0.003  
    공산품  0.089  0.035  
    서비스  0.024  0.012  
미국  농산품  0.004  0.001  
    공산품  0.027  0.010  
    서비스  0.035  0.023  
ROW 농산품  0.109  0.027  
    공산품  1.657  0.235  
    서비스  0.493  1.523

In [329]:
Lv_df = pd.DataFrame(Lv.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['국가', '상품']
Lv_df

한국                   중국                   미국                  ROW  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
국가  상품                                                                          
한국  농산품  0.536  0.015  0.006  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
    공산품  0.116  0.467  0.081  0.004  0.008  0.004  0.002  0.003  0.001  0.002   
    서비스  0.137  0.188  0.751  0.003  0.005  0.003  0.002  0.002  0.001  0.001   
중국  농산품  0.005  0.007  0.003  0.595  0.074  0.027  0.003  0.002  0.001  0.002   
    공산품  0.025  0.044  0.018  0.158  0.537  0.157  0.011  0.015  0.005  0.009   
    서비스  0.015  0.024  0.013  0.130  0.200  0.721  0.006  0.008  0.003  0.006   
미국  농산품  0.003  0.002  0.001  0.002  0.002  0.001  0.504  0.022  0.002  0.002   
    공산품  0.011  0.014  0.007  0.004  0.006  0.003  0.107  0.554  0.036  0.006   
    서비스  0.020  0.024  0.016  0.008  0.011  0.006  0.218  0.245  0.908  0.012   
ROW 농산품  0.012  0.015  0.006  0.014  0.014  0.006  0.032  0.016  0.003  0.698   
    공산품  0.059  0.107  0.045  0.040  0.078  0.035  0.053  0.067  0.016  0.103   
    서비스  0.061  0.094  0.054  0.041  0.066  0.037  0.062  0.065  0.026  0.159   

                       
           공산품    서비스  
국가  상품                 
한국  농산품  0.000  0.000  
    공산품  0.004  0.001  
    서비스  0.003  0.001  
중국  농산품  0.004  0.001  
    공산품  0.022  0.009  
    서비스  0.013  0.006  
미국  농산품  0.002  0.000  
    공산품  0.011  0.004  
    서비스  0.021  0.014  
ROW 농산품  0.062  0.015  
    공산품  0.578  0.082  
    서비스  0.280  0.866

In [330]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')

## 총수출분해

### Eij = Yij+AijXj = Yij + Aij*Xjj + Aij*Xjt + Aij*Xji
한국의 대중 총수출을 분해

In [331]:
# ct_dec = PROD
# nae_dec =nae
# nae_dec
# fd_dec = Fd
# fd_dec

In [332]:
# ct_dec_m = np.tile(ct_dec, reps=[4,1]) # 산출액을 12번 행반복
# Ad_dec =(nae_dec/ct_dec_m)  # 투입계수
# Ad_dec

In [333]:
# Lf_dec = np.linalg.inv(np.identity(4)-Ad_dec)    # 생산유발계수
# Lf_dec

In [334]:
# Lf_dec_out = pd.DataFrame(Lf_dec)
# Lf_dec_out.to_csv('Lf_dec.csv', encoding='utf_8-sig')

In [335]:
E_kc_int = Mt[:3,3:6]  # 한국의 대중 중간재 수출
E_kc_int_sm = E_kc_int.sum(axis=1)
E_kc_fd = Mt[:3,13]  # 한국의 대중 최종재 수출
E_kc = E_kc_int_sm + E_kc_fd # 한국의 대중 총수출
E_kc

array([   0., 1774.,  469.])

In [336]:
Mt[:3,3:6]

array([[   0.,    0.,    0.],
       [  59., 1097.,  340.],
       [  19.,  198.,  147.]])

In [337]:
Y_kc = E_kc_fd  # 한국의 대중국 최종재 수출
Y_kc

array([  0., 278., 105.])

In [338]:
Ct_c = PROD[3:6,]   #중국 산출액
Ct_c_m = np.tile(Ct_c,reps=[3,1])
Ct_c_m

array([[ 22559., 176763., 167403.],
       [ 22559., 176763., 167403.],
       [ 22559., 176763., 167403.]])

In [339]:
A_kc = E_kc_int/Ct_c_m # 한국의 대중중간재수출/중국산출액
A_kc

array([[0.   , 0.   , 0.   ],
       [0.003, 0.006, 0.002],
       [0.001, 0.001, 0.001]])

In [340]:
X_all = Lf@Fd
X_all

array([[   334.033,     52.307,     34.159,     97.5  ],
       [  5992.234,   2640.315,   1488.826,   4568.625],
       [ 16973.482,   1142.883,    628.771,   2100.864],
       [   150.82 ,  18511.319,    849.671,   3047.19 ],
       [  1795.923, 129113.49 ,  10261.471,  35592.116],
       [   609.037, 152847.828,   2909.107,  11037.028],
       [    42.181,    356.838,   3311.44 ,   1125.541],
       [   381.014,   1479.622,  48252.715,   9479.649],
       [   562.578,   2406.438, 273460.988,  17588.996],
       [   253.609,   2339.717,   2610.679,  36265.995],
       [  2811.546,  20939.782,  24569.949, 217410.723],
       [  2076.021,  14124.548,  19806.481, 561211.95 ]])

In [341]:
# Fdd = Fd.sum(axis=1)
# X_all_by_ind = Lf@np.diagflat(Fdd)
# X_all
# X_df = pd.DataFrame(X_all_by_ind)
# X_df.to_csv('X_df.csv')
# f_test = Ad@X_all_by_ind
# f_test_df = pd.DataFrame(f_test)
# f_test_df.to_csv('f_test_df.csv')
# Ad_df =pd.DataFrame(Ad)
Ad_df.to_csv('Ad_df.csv')

In [342]:
X_chn = X_all[3:6,:]  # 모든 국가의 최종수요에 의한 중국의 산출액
print('모든 국가의 최종수요에 의한 중국의 산출액', '\n',X_chn)

모든 국가의 최종수요에 의한 중국의 산출액 
 [[   150.82   18511.319    849.671   3047.19 ]
 [  1795.923 129113.49   10261.471  35592.116]
 [   609.037 152847.828   2909.107  11037.028]]


In [343]:
Akc_by_ind = A_kc@X_chn # 한국의 대중 중간재 수출
print('한국의 대중 중간재 수출', '\n',Akc_by_ind)

한국의 대중 중간재 수출 
 [[   0.       0.       0.       0.   ]
 [  12.777 1160.137   71.814  251.272]
 [   2.674  294.435   14.764   52.127]]


In [344]:
X_chn_agr = Akc_by_ind[0,:] # 한국 대중 농업 중간재 수출의 국가별 분해
X_chn_manu = Akc_by_ind[1,:] # 한국 대중 제조업 중간재 수출의 국가별 분해
X_chn_serv = Akc_by_ind[2,:] # 한국 대중 서비스업 중간재 수출의 국가별 분해

print('한국 대중 농업 중간재 수출의 국가별 분해', '\n',X_chn_agr)
print('한한국 대중 제조업 중간재 수출의 국가별 분해', '\n',X_chn_manu)
print('한국 대중 서비스업 중간재 수출의 국가별 분해', '\n',X_chn_serv)

한국 대중 농업 중간재 수출의 국가별 분해 
 [0. 0. 0. 0.]
한한국 대중 제조업 중간재 수출의 국가별 분해 
 [  12.777 1160.137   71.814  251.272]
한국 대중 서비스업 중간재 수출의 국가별 분해 
 [  2.674 294.435  14.764  52.127]


### 한국의 대중 중간재를 농업, 제조업, 서비스별로 분해 가능

In [386]:
Ex_Kor_to_Chn_decom = np.hstack((Akc_by_ind.reshape([3,4]),Y_kc.reshape([3,1])))
Ex_Kor_to_Chn_decom_sm = Ex_Kor_to_Chn_decom.sum(axis=1)
Ex_Kor_to_Chn_decom

array([[   0.   ,    0.   ,    0.   ,    0.   ,    0.   ],
       [  12.777, 1160.137,   71.814,  251.272,  278.   ],
       [   2.674,  294.435,   14.764,   52.127,  105.   ]])

In [346]:
Ex_Kor_to_Chn_decom_rw_sm = np.hstack((Ex_Kor_to_Chn_decom.reshape([3,5]),Ex_Kor_to_Chn_decom_sm.reshape([3,1]))) # 한국의 대중 수출을 중간재(국가별분해)와 최종재로 표시
Ex_Kor_to_Chn_decom_col_sm = Ex_Kor_to_Chn_decom_rw_sm.sum(axis=0)

In [387]:
Ex_Kor_Chn = np.vstack((Ex_Kor_to_Chn_decom_rw_sm,Ex_Kor_to_Chn_decom_col_sm))
Ex_Kor_Chn

array([[   0.   ,    0.   ,    0.   ,    0.   ,    0.   ,    0.   ],
       [  12.777, 1160.137,   71.814,  251.272,  278.   , 1774.   ],
       [   2.674,  294.435,   14.764,   52.127,  105.   ,  469.   ],
       [  15.451, 1454.572,   86.578,  303.399,  383.   , 2243.   ]])

In [407]:
# Ykc, AkcXcc, AkcXcc, AkcXcu, AkcXcr, AkcXcu+AkcXcr, AkcXck 순으로 배열 변경

Ex_Kor_Chn_f = np.hstack((Ex_Kor_Chn[:,4].reshape([4,1]),Ex_Kor_Chn[:,1].reshape([4,1]),
                          Ex_Kor_Chn[:,2:4],Ex_Kor_Chn[:,2:4].sum(axis=1).reshape([4,1]), Ex_Kor_Chn[:,0].reshape([4,1]),Ex_Kor_Chn[:,-1].reshape([4,1])))

Ex_Kor_Chn_ratio =  (Ex_Kor_Chn_f/(np.tile(Ex_Kor_Chn[:,-1].reshape([4,1]), reps=[1,7])))*100
print('한국의 대중 총수출 분해', '\n', Ex_Kor_Chn_ratio.round(1))



한국의 대중 총수출 분해 
 [[  nan   nan   nan   nan   nan   nan   nan]
 [ 15.7  65.4   4.   14.2  18.2   0.7 100. ]
 [ 22.4  62.8   3.1  11.1  14.3   0.6 100. ]
 [ 17.1  64.8   3.9  13.5  17.4   0.7 100. ]]


In [408]:
Ex_Kor_Chn_f

array([[   0.   ,    0.   ,    0.   ,    0.   ,    0.   ,    0.   ,
           0.   ],
       [ 278.   , 1160.137,   71.814,  251.272,  323.086,   12.777,
        1774.   ],
       [ 105.   ,  294.435,   14.764,   52.127,   66.891,    2.674,
         469.   ],
       [ 383.   , 1454.572,   86.578,  303.399,  389.977,   15.451,
        2243.   ]])

In [409]:
(np.tile(Ex_Kor_Chn[:,-1].reshape([4,1]), reps=[1,7]))

array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [1774., 1774., 1774., 1774., 1774., 1774., 1774.],
       [ 469.,  469.,  469.,  469.,  469.,  469.,  469.],
       [2243., 2243., 2243., 2243., 2243., 2243., 2243.]])

In [410]:
Ex_Kor_to_Chn_decom_rw_sm

array([[   0.   ,    0.   ,    0.   ,    0.   ,    0.   ,    0.   ],
       [  12.777, 1160.137,   71.814,  251.272,  278.   , 1774.   ],
       [   2.674,  294.435,   14.764,   52.127,  105.   ,  469.   ]])

In [411]:
Ex_Kor_Chn_df = pd.DataFrame(Ex_Kor_Chn.round(3), columns = [['중간재', '중간재', '중간재', '중간재', '최종재','총수출'],
                                    ['한국', '중국', '미국', 'ROW', '중국','중국']],

                                    index=['농업', '공업', '서비스','소계'])
Ex_Kor_Chn_df.index.names=['산업']
Ex_Kor_Chn_df

중간재                               최종재     총수출
         한국        중국      미국      ROW     중국      중국
산업                                                   
농업    0.000     0.000   0.000    0.000    0.0     0.0
공업   12.777  1160.137  71.814  251.272  278.0  1774.0
서비스   2.674   294.435  14.764   52.127  105.0   469.0
소계   15.451  1454.572  86.578  303.399  383.0  2243.0

In [412]:
Ex_Kor_Chn_df.to_csv('한국의 대중수출분해.csv', encoding='utf_8-sig')

In [413]:
print('대중수출_거래표 \n',E_kc, '\n')
print('대중수출_분해합 \n',Ex_Kor_Chn[:,-1], '\n')

대중수출_거래표 
 [   0. 1774.  469.] 

대중수출_분해합 
 [   0. 1774.  469. 2243.] 



## DVA 와 FVA 구하기(OECD의 총수출을 이용하는 개념을 이용)
### 한국의 산업별 DVA 및FVA 구하기

In [414]:
import scipy.linalg as linalg

In [415]:
Mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
Mtx_for_tra=np.where(Mtx_for_int == 1, 0, 1)

Mtx_for_fnl= linalg.block_diag(np.ones((3,1)),np.ones((3,1)),np.ones((3,1)),np.ones((3,1)))
Mtx_for_fnl_tra=np.where(Mtx_for_fnl == 1, 0, 1)

INT = Icio_2[0:12,0:12].astype(float)

EXIM_INT_mt = (INT*Mtx_for_tra).reshape([12,12])  # 중간재 수출입
EXGR_INT = EXIM_INT_mt.sum(axis=1).reshape([12,1])

FD = Icio_2[0:12,12:16].astype(float)

EXIM_FNL_mt = (FD*Mtx_for_fnl_tra).reshape([12,4])  # 최종재 수출입
EXGR_FNL = EXIM_FNL_mt.sum(axis=1).reshape([12,1])

EXGR = EXGR_INT + EXGR_FNL
EXGR

array([[   12.],
       [ 5118.],
       [ 1488.],
       [  282.],
       [21494.],
       [ 4860.],
       [  944.],
       [ 8051.],
       [11906.],
       [ 1826.],
       [30708.],
       [16000.]])

In [416]:
EXGR_decom = Lv@np.diagflat(EXGR)
EXGR_decom

array([[    6.428,    78.806,     8.616,     0.041,     5.631,     0.618,
            0.082,     1.102,     0.388,     0.149,     4.628,     0.821],
       [    1.388,  2388.34 ,   119.961,     1.174,   162.879,    17.634,
            2.135,    23.368,     9.219,     3.364,   123.536,    21.524],
       [    1.645,   960.535,  1118.21 ,     0.917,   114.065,    14.428,
            1.528,    15.712,     8.432,     2.496,    88.032,    21.664],
       [    0.058,    33.683,     4.091,   167.73 ,  1587.746,   133.554,
            2.421,    19.628,     8.729,     3.556,   108.581,    21.029],
       [    0.304,   222.683,    27.001,    44.685, 11539.443,   764.253,
           10.842,   121.353,    58.693,    17.169,   681.093,   138.166],
       [    0.183,   124.6  ,    19.989,    36.655,  4296.892,  3504.511,
            5.953,    66.056,    36.648,    10.198,   384.767,   100.306],
       [    0.035,     9.321,     1.099,     0.643,    33.697,     2.995,
          475.312,   177.534,   

In [417]:
# EXGR_Kor_by_ind = EXGR_decom[:,:3]
# EXGR_Kor_by_ind

In [418]:
# print(EXGR_Kor_by_ind.sum(axis=0))

In [419]:
EXGR_decom_df = pd.DataFrame(EXGR_decom.round(3), columns = [['한국', '한국', '한국','중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']],

                                    index=[['한국', '한국', '한국','중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']])
EXGR_decom_df

한국                           중국                            미국  \
            농업        공업       서비스       농업         공업       서비스       농업   
한국  농업   6.428    78.806     8.616    0.041      5.631     0.618    0.082   
    공업   1.388  2388.340   119.961    1.174    162.879    17.634    2.135   
    서비스  1.645   960.535  1118.210    0.917    114.065    14.428    1.528   
중국  농업   0.058    33.683     4.091  167.730   1587.746   133.554    2.421   
    공업   0.304   222.683    27.001   44.685  11539.443   764.253   10.842   
    서비스  0.183   124.600    19.989   36.655   4296.892  3504.511    5.953   
미국  농업   0.035     9.321     1.099    0.643     33.697     2.995  475.312   
    공업   0.134    73.872    10.075    1.073    122.359    13.660  101.273   
    서비스  0.236   124.335    23.226    2.280    226.572    29.261  206.234   
ROW 농업   0.145    77.442     9.590    3.942    304.863    29.205   29.999   
    공업   0.712   545.517    66.274   11.266   1672.550   172.223   49.643   
    서비스  0.732   478.865    79.868   11.594   1427.302   177.658   58.579   

                                   ROW                        
               공업        서비스        농업         공업        서비스  
한국  농업      1.102      0.388     0.149      4.628      0.821  
    공업     23.368      9.219     3.364    123.536     21.524  
    서비스    15.712      8.432     2.496     88.032     21.664  
중국  농업     19.628      8.729     3.556    108.581     21.029  
    공업    121.353     58.693    17.169    681.093    138.166  
    서비스    66.056     36.648    10.198    384.767    100.306  
미국  농업    177.534     21.765     3.482     49.876      6.691  
    공업   4463.199    424.138    10.381    347.518     64.908  
    서비스  1975.809  10805.893    21.974    651.512    219.703  
ROW 농업    128.235     33.263  1275.296   1917.801    245.628  
    공업    536.481    190.933   188.219  17750.244   1311.098  
    서비스   522.523    307.898   289.718   8600.414  13848.460

In [420]:
EXGR_decom_df.to_csv('DVA_FVA_매트릭스.csv', encoding='utf_8-sig')

In [421]:
# 한국의 총수출의 부가가치 분해

Kor_tr_va = EXGR_decom[:,:3]

Kor_exgr = EXGR[:3,:].sum() # 한국의 총수출
Kor_ex = np.vstack((Kor_tr_va[:,:3].sum(axis=0).reshape([3,1]),Kor_exgr)) # 산업별, 총수출 벡터
Kor_ex


array([[  12.],
       [5118.],
       [1488.],
       [6618.]])

In [422]:
# DVA
Arg_dva = Kor_tr_va[:3,0].sum()
Manu_dva = Kor_tr_va[:3,1].sum()
Serv_dva = Kor_tr_va[:3,2].sum()
Dva_all = np.vstack((Arg_dva, Manu_dva, Serv_dva))
Dva_all

array([[   9.46 ],
       [3427.681],
       [1246.787]])

In [423]:
# FVA(중국,미국,Row, 총Fva 순)

Arg_fva = np.hstack((Kor_tr_va[3:6,0].sum(),Kor_tr_va[6:9,0].sum(),Kor_tr_va[9:12,0].sum(),Kor_tr_va[3:12,0].sum()) )
Manu_fva  = np.hstack((Kor_tr_va[3:6,1].sum(),Kor_tr_va[6:9,1].sum(),Kor_tr_va[9:12,1].sum(),Kor_tr_va[3:12,1].sum()) )
Serv_fva  = np.hstack((Kor_tr_va[3:6,2].sum(),Kor_tr_va[6:9,2].sum(),Kor_tr_va[9:12,2].sum(),Kor_tr_va[3:12,2].sum()) )
Fva_all = np.vstack((Arg_fva, Manu_fva, Serv_fva))
Fva_all

array([[   0.546,    0.405,    1.589,    2.54 ],
       [ 380.966,  207.529, 1101.825, 1690.319],
       [  51.081,   34.4  ,  155.732,  241.213]])

In [424]:
 # 한국 총수출의 부가가치 기준 분해

Dva_fva_mt = np.hstack((Dva_all, Fva_all))
Dva_fva_mt_cl_sm = Dva_fva_mt.sum(axis=0).reshape(1,5)
Dva_fva_mt_f = np.vstack((Dva_fva_mt, Dva_fva_mt_cl_sm))
Dva_fva_mt_f

array([[   9.46 ,    0.546,    0.405,    1.589,    2.54 ],
       [3427.681,  380.966,  207.529, 1101.825, 1690.319],
       [1246.787,   51.081,   34.4  ,  155.732,  241.213],
       [4683.928,  432.592,  242.334, 1259.146, 1934.072]])

In [425]:
 Dva_fva_mt_ratio =  Dva_fva_mt_f/(np.tile(Kor_ex, reps=[1,5]))
 print('한국 총수출의 부가가치 기준 분해', '\n', (Dva_fva_mt_ratio*100).round(1))

한국 총수출의 부가가치 기준 분해 
 [[78.8  4.5  3.4 13.2 21.2]
 [67.   7.4  4.1 21.5 33. ]
 [83.8  3.4  2.3 10.5 16.2]
 [70.8  6.5  3.7 19.  29.2]]


##Tiva_in and Tiva_out

In [426]:
Fd_kor = Fd[:,0]
Fd_non_kor = Fd[:,1:].sum(axis=1)
Fd_non_kor

array([     3.,   1518.,    449.,   5794.,  37307., 102891.,   1228.,
        27508., 180037.,  15220.,  86804., 344618.])

In [427]:
Tiva_by_nonkor_fd = Lv@Fd_non_kor
Kor_tiva_in = Tiva_by_nonkor_fd[:3,]   # 한국의 Tiva_in(산업별 구분, DAX와 동일)
Kor_tiva_in_all = Kor_tiva_in.reshape([3,1])

In [428]:
Tiva_by_kor_fd = Lv@Fd_kor
Kor_tiva_out = Tiva_by_kor_fd[3:]   # 한국의 Tiva_out(산업별 구분, FVA와 동일)
Kor_tiva_out_arg = Kor_tiva_out[0]+Kor_tiva_out[3]+Kor_tiva_out[6]  # 농업
Kor_tiva_out_manu = Kor_tiva_out[1]+Kor_tiva_out[4]+Kor_tiva_out[7]  # 제조업
Kor_tiva_out_serv = Kor_tiva_out[2]+Kor_tiva_out[5]+Kor_tiva_out[8]  # 서비스
Kor_tiva_out_all = np.vstack((Kor_tiva_out_arg,Kor_tiva_out_manu,Kor_tiva_out_serv))

In [429]:
Kor_tiva_net = Kor_tiva_in_all- Kor_tiva_out_all   # 순이출입
Kor_tiva = np.hstack((Kor_tiva_in_all,Kor_tiva_out_all, Kor_tiva_net))
Kor_tiva_rw_sm = Kor_tiva.sum(axis=0)
Kor_tiva_f = np.vstack((Kor_tiva, Kor_tiva_rw_sm))
print('한국의 부가가치 수출 및 수입', '\n', Kor_tiva_f.round(0))

한국의 부가가치 수출 및 수입 
 [[  93.  230. -137.]
 [2488. 1588.  900.]
 [2064. 1837.  227.]
 [4645. 3655.  990.]]


In [430]:
Tiva_by_nonkor_fd = Lv@Fd_non_kor
Kor_tiva_in = Tiva_by_nonkor_fd[:3]   # 한국의 Tiva_in(산업별 구분, DAX와 동일)

In [431]:
Kor_tiva_f_df = pd.DataFrame(Kor_tiva_f.round(0), columns = ['수출', '수입', '순수출'],

                                    index = ['농업', '공업', '서비스', '전부문'])
Kor_tiva_f_df

수출      수입    순수출
농업     93.0   230.0 -137.0
공업   2488.0  1588.0  900.0
서비스  2064.0  1837.0  227.0
전부문  4645.0  3655.0  990.0

In [432]:
Kor_tiva_f_df.to_csv('한국의 부가가치 수출입.csv', encoding='utf_8-sig')


### 전후방참여도 구하기

In [433]:
Ex_one = Trade.sum(axis=1) # 각국의 총수출액

In [434]:
Prt = (Cd_for_nae@EXGR_decom)@Cd_for_nae.T # DVA_FVA 매트릭스(12x12)를 1국 1산업으로 부문통합(4x4)
Prt


array([[ 4683.928,   317.387,    61.966,   266.214],
       [  432.592, 22075.469,   330.323,  1464.864],
       [  242.334,   432.541, 18651.158,  1376.044],
       [ 1259.146,  3810.603,  1857.553, 45426.878]])

In [435]:
One_diag = np.ones((4,4))
np.fill_diagonal(One_diag,0)
One_diag

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.]])

In [439]:
Prt_mtx = Prt*One_diag  # 자국을 제외한 DVA_FVA 매트릭스
print('1국 1산업 DVA_FVA 매트릭스', '\n', Prt_mtx)

1국 1산업 DVA_FVA 매트릭스 
 [[   0.     317.387   61.966  266.214]
 [ 432.592    0.     330.323 1464.864]
 [ 242.334  432.541    0.    1376.044]
 [1259.146 3810.603 1857.553    0.   ]]


In [440]:
Bwd_participation_one = Prt_mtx.sum(axis=0)/Ex_one   # 후방참여도
Fwd_participation_one = Prt_mtx.sum(axis=1)/Ex_one   # 전방참여도
participation_one = np.hstack((Bwd_participation_one.T.reshape([4,1]),Fwd_participation_one.reshape([4,1])))
print('국가별 전후방 참여도', '\n', (participation_one*100).round(1))

국가별 전후방 참여도 
 [[29.2  9.8]
 [17.1  8.4]
 [10.8  9.8]
 [ 6.4 14.3]]


In [438]:
participation_one_df = pd.DataFrame(participation_one.round(3), columns = ['후방참여도','전방참여도'],

                                    index=['한국', '중국', '미국','ROW'])
participation_one_df

후방참여도  전방참여도
한국   0.292  0.098
중국   0.171  0.084
미국   0.108  0.098
ROW  0.064  0.143