<a href="https://colab.research.google.com/github/Tom-Jung/IO_with_python/blob/main/%EB%B6%80%EB%A1%9D.%20%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [2]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

# 부문통합하여 3부문 IO표 만들기
- 2019년 산업연관표(33부문)를 IO표를 3부문 IO표로 통합하고 이를 통해 설명하기로 함
- 33부문을 크게 농수산품, 공산품 및 서비스로 통합하기 위하여 행렬 곱을 사용
- 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타낸다

In [3]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [4]:
cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
ccdd = pd.read_csv(cdd)
cd_for_itr = ccdd.to_numpy().reshape(33,2)
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
print('3부문 코드 : \n', cd_3)
print('33부문 코드 : \n', cd_33)

3부문 코드 : 
 [1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
33부문 코드 : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]


In [5]:
Mtx = np.zeros((3,33)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###  총거래표

In [6]:
url_Tt_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [7]:
Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [8]:
nae_tot_row = code@Tot_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row

array([[  4.,   0.,  36.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  10.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [ 16.,   0.,  41.,  41.,  20.,  88., 146.,  17.,  82.,  50., 139.,
         63.,  77., 153.,  11.,  16.,  47.,   2., 103.,  18.,  41.,  57.,
         11.,   4.,   4.,  31.,   6.,   8.,   7.,  39.,   7.,  16.,   0.],
       [  7.,   1.,  24.,  11.,   9.,  11.,  52.,  10.,  27.,  12.,  28.,
         13.,  17.,  29.,   4.,   9.,  19.,   5.,  46., 112.,  56.,  44.,
         54.,  72.,  58.,  83.,  23.,  26.,  28.,  38.,  14.,  12.,   3.]])

In [9]:
nae_tot_row.shape  # 행과 열의 개수 확인

(3, 33)

In [10]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col

array([[  4.,  38.,  11.],
       [ 16., 944., 401.],
       [  7., 257., 693.]])

In [11]:
ztest_nae_tot_col = nae_tot_row@Mtx.T # 반복문을 이용해서 만든  Mtx 이용
ztest_nae_tot_col

array([[  4.,  38.,  11.],
       [ 16., 944., 401.],
       [  7., 257., 693.]])

In [12]:
print(nae_tot_col.shape)  # 행과 열의 개수 확인
print(nae_tot_col.sum())  # 중간투입(수요) 합계 확인

(3, 3)
2371.0


In [13]:

nae_tot_col.sum()

2371.0

In [14]:
va_row = Tot_33[33:40,0:33]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[  27., 1239., 1105.],
       [   7.,  197.,  714.],
       [  20.,  152.,  298.],
       [   5.,  144.,  230.],
       [   1.,   60.,  100.],
       [  33.,  553., 1342.],
       [  60., 1792., 2447.]])

In [15]:
va_row.shape

(7, 3)

In [16]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [17]:
fd = Tot_33[0:33, 34:45]
fd

array([[ 18.,   0.,   0.,   0.,   0.,   0.,   1.,  19.,  72.],
       [  0.,   0.,   0.,   0.,   2.,   0.,   0.,   2., 149.],
       [ 67.,   0.,   0.,   0.,   1.,   0.,   9.,  77., 168.],
       [ 35.,   0.,   0.,   0.,   1.,   0.,  24.,  60.,  97.],
       [  1.,   0.,   0.,   0.,   1.,   0.,   4.,   6.,  52.],
       [ 16.,   0.,   0.,   0.,   1.,   0.,  52.,  69., 165.],
       [ 11.,   0.,   0.,   0.,   6.,   0., 104., 121., 355.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   5.,  45.],
       [ -1.,   0.,  -3.,   0.,   1.,   0.,  44.,  41., 181.],
       [  2.,   0.,   3.,   4.,   1.,   0.,  12.,  22., 108.],
       [ 27.,   0.,  26.,   5.,   3.,   0., 173., 234., 383.],
       [  9.,   0.,  10.,   0.,   1.,   0.,  31.,  51., 128.],
       [  3.,   0.,  57.,   0.,  -1.,   0.,  60., 119., 175.],
       [ 33.,   0.,  29.,  11.,   2.,   0., 104., 179., 263.],
       [ 10.,   0.,   4.,   0.,   0.,   2.,   4.,  20.,  30.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   2.,   2.,

In [18]:
fd_row=code@fd@fd_cd.T
fd_row

array([[  18.,    0.,    1.,   19.,   72.],
       [ 213.,  167.,  628., 1008., 2369.],
       [1032.,  432.,  131., 1595., 2552.]])

In [19]:
fd_row_sm = np.sum((fd_row), axis=0) # 최종수요의 행합

In [20]:
fd_sm=fd_row_sm.reshape(1,5)

In [21]:
nae_va_ct = np.concatenate((nae_tot_col, va_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct

array([[   4.,   38.,   11.],
       [  16.,  944.,  401.],
       [   7.,  257.,  693.],
       [  27., 1239., 1105.],
       [   7.,  197.,  714.],
       [  20.,  152.,  298.],
       [   5.,  144.,  230.],
       [   1.,   60.,  100.],
       [  33.,  553., 1342.],
       [  60., 1792., 2447.]])

In [22]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [23]:
nnull = np.zeros((6,5)) # 0행렬

In [24]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [25]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
tot_f_va1 = np.concatenate((tot_f[0:4,], tot_f[-2:,:]), axis=0)  # 최종 3x3 부문통합된 거래표
tot_f_va1

array([[   4.,   38.,   11.,   53.,   18.,    0.,    1.,   19.,   72.],
       [  16.,  944.,  401., 1361.,  213.,  167.,  628., 1008., 2369.],
       [   7.,  257.,  693.,  957., 1032.,  432.,  131., 1595., 2552.],
       [  27., 1239., 1105., 2371., 1263.,  599.,  760., 2622., 4993.],
       [  33.,  553., 1342., 1928.,    0.,    0.,    0.,    0.,    0.],
       [  60., 1792., 2447., 4299.,    0.,    0.,    0.,    0.,    0.]])

In [26]:
tot_F = pd.DataFrame(tot_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [27]:
tot_F_va1= pd.DataFrame(tot_f_va1, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [28]:
# tot_F.reset_index(inplace=True) # 인덱스 설정(부문명)

In [29]:
# tot_F_va1.reset_index(inplace=True)# 인덱스 설정(부문명)

In [30]:
tot_F_va1  #최종 3x3 거래표 확인

농산품     공산품     서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
농산품     4.0    38.0    11.0    53.0    18.0    0.0    1.0    19.0    72.0
공산품    16.0   944.0   401.0  1361.0   213.0  167.0  628.0  1008.0  2369.0
서비스     7.0   257.0   693.0   957.0  1032.0  432.0  131.0  1595.0  2552.0
중간투입계  27.0  1239.0  1105.0  2371.0  1263.0  599.0  760.0  2622.0  4993.0
부가가치계  33.0   553.0  1342.0  1928.0     0.0    0.0    0.0     0.0     0.0
총투입액   60.0  1792.0  2447.0  4299.0     0.0    0.0    0.0     0.0     0.0

###  국산거래표

In [31]:
url_Dm_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix.csv"  # 33부문의 국산거래표 불러오기
Dm_33 = pd.read_csv(url_Dm_33)

In [32]:
Dmm_33 = Dm_33.to_numpy()
Dom_33 = Dmm_33[0:34,1:53].astype(float)

In [33]:
nae_dom_row = code@Dom_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_dom_row

array([[  4.,   0.,  31.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [ 15.,   0.,  31.,  20.,  15.,   7.,  89.,  14.,  38.,  45.,  67.,
         47.,  60., 131.,   8.,  16.,   9.,   2.,  95.,  16.,  33.,  49.,
          7.,   4.,   4.,  28.,   6.,   8.,   7.,  31.,   7.,  16.,   0.],
       [  7.,   1.,  24.,  11.,   9.,  11.,  49.,  10.,  26.,  12.,  24.,
         12.,  16.,  25.,   4.,   9.,  19.,   5.,  45., 106.,  36.,  44.,
         47.,  66.,  57.,  80.,  21.,  23.,  28.,  38.,  14.,  12.,   3.]])

In [34]:
nae_dom_row.shape  # 행과 열의 개수 확인

(3, 33)

In [35]:
nae_dom_col = nae_dom_row@code.T  # 수작업한 code 이용
nae_dom_col

array([[  4.,  31.,  10.],
       [ 15., 588., 322.],
       [  7., 243., 644.]])

In [36]:
print(nae_dom_col.shape)  # 행과 열의 개수 확인
print(nae_dom_col.sum())  # 중간투입(수요) 확인

(3, 3)
1864.0


In [37]:
dsm_row = Dom_33[33:34,0:33]@code.T # 중투합
dsm_row

array([[ 26., 862., 976.]])

In [38]:
dsm_row.shape

(1, 3)

In [39]:
dfd = Dom_33[0:33, 34:45]
dfd

array([[ 15.,   0.,   0.,   0.,  -1.,   0.,   1.,  15.,  60.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.],
       [ 52.,   0.,   0.,   0.,   1.,   0.,   9.,  62., 135.],
       [ 16.,   0.,   0.,   0.,   1.,   0.,  23.,  40.,  66.],
       [  1.,   0.,   0.,   0.,   1.,   0.,   4.,   6.,  46.],
       [ 15.,   0.,   0.,   0.,   1.,   0.,  52.,  68., 136.],
       [  3.,   0.,   0.,   0.,   5.,   0., 101., 109., 279.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   5.,  40.],
       [ -1.,   0.,  -3.,   0.,   1.,   0.,  44.,  41., 141.],
       [  1.,   0.,   3.,   3.,   1.,   0.,  12.,  20., 101.],
       [ 15.,   0.,  10.,   2.,   2.,   0., 172., 201., 285.],
       [  6.,   0.,   8.,   0.,   1.,   0.,  31.,  46., 108.],
       [  2.,   0.,  37.,   0.,  -1.,   0.,  60.,  98., 138.],
       [ 24.,   0.,  19.,   8.,   2.,   0., 104., 157., 233.],
       [  4.,   0.,   3.,   0.,   0.,   1.,   4.,  12.,  21.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   2.,   2.,

In [40]:
dfd_row=code@dfd@fd_cd.T

In [41]:
dfd_row_sm = np.sum((dfd_row), axis=0) # 최종수요의 행합

In [42]:
dfd_sm=dfd_row_sm.reshape(1,5)
dfd_sm

array([[1150.,  530.,  755., 2435., 4299.]])

In [43]:
nae_dm = np.concatenate((nae_dom_col, dsm_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_dm

array([[  4.,  31.,  10.],
       [ 15., 588., 322.],
       [  7., 243., 644.],
       [ 26., 862., 976.]])

In [44]:
nae_col_sm_dm = nae_dm.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [45]:
nae_dm_sm = nae_col_sm_dm.sum(axis=1).reshape(4,1)  # 부가가치 및 산출액의 열합

In [46]:
dfd_nnull = np.concatenate((dfd_row, dfd_sm),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [47]:
dom_f = np.concatenate((nae_dm, nae_dm_sm, dfd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
dom_f

array([[   4.,   31.,   10.,   45.,   15.,   -1.,    1.,   15.,   60.],
       [  15.,  588.,  322.,  925.,  138.,  106.,  623.,  867., 1792.],
       [   7.,  243.,  644.,  894.,  997.,  425.,  131., 1553., 2447.],
       [  26.,  862.,  976., 1864., 1150.,  530.,  755., 2435., 4299.]])

In [48]:
dom_F = pd.DataFrame(dom_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
dom_F

농산품    공산품    서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
농산품     4.0   31.0   10.0    45.0    15.0   -1.0    1.0    15.0    60.0
공산품    15.0  588.0  322.0   925.0   138.0  106.0  623.0   867.0  1792.0
서비스     7.0  243.0  644.0   894.0   997.0  425.0  131.0  1553.0  2447.0
중간투입계  26.0  862.0  976.0  1864.0  1150.0  530.0  755.0  2435.0  4299.0

In [49]:
# dom_F.reset_index(inplace=True)# 인덱스 설정(부문명)
# dom_F

### 수입거래표

In [50]:

url_Im_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix.csv"  # 33부문의 수입거래표 불러오기
Im_33 = pd.read_csv(url_Im_33)
Im_33

부문  농림수산품  광산품  음식료품  섬유 및 가죽제품  목재 및 종이, 인쇄  석탄 및 석유제품  \
0                 농림수산품      0    0     5          1            0          0   
1                   광산품      0    0     0          0            0         77   
2                  음식료품      0    0    10          1            0          0   
3             섬유 및 가죽제품      0    0     0         11            0          0   
4           목재 및 종이, 인쇄      0    0     0          0            5          0   
5             석탄 및 석유제품      0    0     0          0            0          3   
6                  화학제품      1    0     0          2            0          1   
7               비금속광물제품      0    0     0          0            0          0   
8               1차 금속제품      0    0     0          0            0          0   
9                금속가공제품      0    0     0          0            0          0   
10       컴퓨터, 전자 및 광학기기      0    0     0          0            0          0   
11                 전기장비      0    0     0          0            0          0   
12              기계 및 장비      0    0     0          0            0          0   
13                 운송장비      0    0     0          0            0          0   
14            기타 제조업 제품      0    0     0          0            0          0   
15    제조임가공 및 산업용 장비 수리      0    0     0          7            0          0   
16          전력, 가스 및 증기      0    0     0          0            0          0   
17   수도, 폐기물처리 및 재활용서비스      0    0     0          0            0          0   
18                   건설      0    0     0          0            0          0   
19        도소매 및 상품중개서비스      0    0     0          0            0          0   
20                운송서비스      0    0     0          0            0          0   
21          음식점 및 숙박서비스      0    0     0          0            0          0   
22        정보통신 및 방송 서비스      0    0     0          0            0          0   
23          금융 및 보험 서비스      0    0     0          0            0          0   
24               부동산서비스      0    0     0          0            0          0   
25      전문, 과학 및 기술 서비스      0    0     0          0            0          0   
26              사업지원서비스      0    0     0          0            0          0   
27      공공행정, 국방 및 사회보장      0    0     0          0            0          0   
28                교육서비스      0    0     0          0            0          0   
29        보건 및 사회복지 서비스      0    0     0          0            0          0   
30  예술, 스포츠 및 여가 관련 서비스      0    0     0          0            0          0   
31               기타 서비스      0    0     0          0            0          0   
32                   기타      0    0     0          0            0          0   
33                중간투입계      1    0    15         22            5         81   

    화학제품  비금속광물제품  1차 금속제품  ...  중간수요계  민간소비지출\n(가계 및 가계봉사\n비영리단체)  정부소비지출  \
0      1        0        0  ...      8                           3       0   
1      6        1       23  ...    144                           0       0   
2      0        0        0  ...     18                          15       0   
3      0        0        0  ...     11                          19       0   
4      0        0        0  ...      6                           0       0   
5     16        0        0  ...     28                           1       0   
6     34        1        0  ...     64                           8       0   
7      0        1        0  ...      5                           0       0   
8      1        0       21  ...     40                           0       0   
9      0        0        0  ...      5                           1       0   
10     0        0        0  ...     65                          12       0   
11     0        0        0  ...     15                           3       0   
12     0        0        0  ...     16                           1       0   
13     0        0        0  ...      8                           9       0   
14     0        0        0  ...      1            

In [51]:
Imm_33 = Im_33.to_numpy()
Imp_33 = Imm_33[0:34,1:53].astype(float)

In [52]:
nae_imp_row = code@Imp_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_imp_row

array([[ 0.,  0.,  5.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0., 10., 21.,  5., 81., 57.,  3., 44.,  5., 72., 16., 17.,
        22.,  3.,  0., 38.,  0.,  8.,  2.,  8.,  8.,  4.,  0.,  0.,  3.,
         0.,  0.,  0.,  8.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,  1.,  0.,  4.,  1.,  1.,
         4.,  0.,  0.,  0.,  0.,  1.,  6., 20.,  0.,  7.,  6.,  1.,  3.,
         2.,  3.,  0.,  0.,  0.,  0.,  0.]])

In [53]:
nae_imp_row.shape  # 행과 열의 개수 확인

(3, 33)

In [54]:
nae_imp_col = nae_imp_row@code.T  # 수작업한 code 이용
nae_imp_col

array([[  0.,   7.,   1.],
       [  1., 356.,  79.],
       [  0.,  14.,  49.]])

In [55]:
print(nae_imp_col.shape)  # 행과 열의 개수 확인
print(nae_imp_col.sum())  # 중간투입(수요) 확인

(3, 3)
507.0


In [56]:
ism_row = Imp_33[33:34,0:33]@code.T # 중투합
ism_row

array([[  1., 377., 129.]])

In [57]:
ism_row.shape

(1, 3)

In [58]:
ifd = Imp_33[0:33, 34:45] #수입최종수요
ifd

array([[  3.,   0.,   0.,   0.,   1.,   0.,   0.,   4.,  12.],
       [  0.,   0.,   0.,   0.,   2.,   0.,   0.,   2., 146.],
       [ 15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,  33.],
       [ 19.,   0.,   0.,   0.,   0.,   0.,   1.,  20.,  31.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   6.],
       [  1.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,  29.],
       [  8.,   0.,   0.,   0.,   1.,   0.,   3.,  12.,  76.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   5.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  40.],
       [  1.,   0.,   0.,   1.,   0.,   0.,   0.,   2.,   7.],
       [ 12.,   0.,  16.,   3.,   1.,   0.,   1.,  33.,  98.],
       [  3.,   0.,   2.,   0.,   0.,   0.,   0.,   5.,  20.],
       [  1.,   0.,  20.,   0.,   0.,   0.,   0.,  21.,  37.],
       [  9.,   0.,  10.,   3.,   0.,   0.,   0.,  22.,  30.],
       [  6.,   0.,   1.,   0.,   0.,   1.,   0.,   8.,   9.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,

In [59]:
ifd_row=code@ifd@fd_cd.T

In [60]:
ifd_row_sm = np.sum((ifd_row), axis=0) # 최종수요의 행합

In [61]:
ifd_sm=ifd_row_sm.reshape(1,5)
ifd_sm

array([[113.,  69.,   5., 187., 694.]])

In [62]:
nae_im = np.concatenate((nae_imp_col, ism_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_im

array([[  0.,   7.,   1.],
       [  1., 356.,  79.],
       [  0.,  14.,  49.],
       [  1., 377., 129.]])

In [63]:
nae_col_sm_imp = nae_im.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [64]:
nae_im_sm = nae_col_sm_imp.sum(axis=1).reshape(4,1)  # 부가가치 및 산출액의 열합

In [65]:
ifd_nnull = np.concatenate((ifd_row, ifd_sm),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [66]:
imp_f = np.concatenate((nae_im, nae_im_sm, ifd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
imp_f

array([[  0.,   7.,   1.,   8.,   3.,   1.,   0.,   4.,  12.],
       [  1., 356.,  79., 436.,  75.,  61.,   5., 141., 577.],
       [  0.,  14.,  49.,  63.,  35.,   7.,   0.,  42., 105.],
       [  1., 377., 129., 507., 113.,  69.,   5., 187., 694.]])

In [67]:
imp_F = pd.DataFrame(imp_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
imp_F

농산품    공산품    서비스  중간수요계     소비    투자   수출  최종수요계   총수요계
농산품    0.0    7.0    1.0    8.0    3.0   1.0  0.0    4.0   12.0
공산품    1.0  356.0   79.0  436.0   75.0  61.0  5.0  141.0  577.0
서비스    0.0   14.0   49.0   63.0   35.0   7.0  0.0   42.0  105.0
중간투입계  1.0  377.0  129.0  507.0  113.0  69.0  5.0  187.0  694.0

In [68]:
# imp_F.reset_index(inplace=True)# 인덱스 설정(부문명)
# imp_F

In [69]:
# 총, 국산, 수입거래표 내보내기
tot_F.to_csv('총거래표_3부문.csv', encoding="utf-8-sig")
tot_F_va1.to_csv('총거래표_부가가치1개.csv', encoding="utf-8-sig")
dom_F.to_csv('국산거래표_3부문.csv', encoding="utf-8-sig")
imp_F.to_csv('수입거래표_3부문.csv', encoding="utf-8-sig")

## 취업(고용)인원

In [70]:
url_emp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Employment.csv"  # 취업(고용) 인원불러오기
emp_3s = pd.read_csv(url_emp)

In [71]:
emp = emp_3s.to_numpy()
empp = emp[:-1,2:] #인원만 가져오기
empp

array([[1274565, 101980],
       [15386, 14339],
       [332905, 264836],
       [241658, 181274],
       [161117, 129459],
       [11198, 11198],
       [434660, 400718],
       [105523, 89356],
       [125988, 120328],
       [339958, 291792],
       [383368, 357894],
       [238735, 219090],
       [404564, 359388],
       [447437, 434111],
       [148587, 103204],
       [485468, 454088],
       [60855, 60011],
       [148931, 128089],
       [1783323, 1412251],
       [3351053, 2023265],
       [1409388, 816245],
       [1944097, 1080419],
       [704655, 634801],
       [660708, 627574],
       [579767, 362045],
       [1512663, 1345036],
       [1146140, 1061694],
       [1139797, 1139797],
       [1532641, 1205999],
       [1789727, 1702895],
       [478095, 294933],
       [1163630, 680948],
       [0, 0]], dtype=object)

In [72]:
emp_3=code@empp
emp_sm = emp_3.sum(axis=0).reshape([1,2])
emp_3_f = np.concatenate((emp_3,emp_sm), axis=0)
emp_3_f

array([[1274565, 101980],
       [3876552, 3431075],
       [19405470, 14576002],
       [24556587, 18109057]], dtype=object)

In [73]:
emp_F = pd.DataFrame(emp_3_f, columns = ['취업자수', '피용자수'],
                     index=['농산품', '공산품', '서비스', '총계']) # 변수명 붙여서 pandas로 내보내기
emp_F

취업자수      피용자수
농산품   1274565    101980
공산품   3876552   3431075
서비스  19405470  14576002
총계   24556587  18109057

In [74]:
emp_F.to_csv('고용표_3부문.csv', encoding="utf-8-sig")